### ISSUE TITLE
Incorrect domain name?

### ISSUE THREAD

**Issue by Tancred423** [LukeSmithxyz/emailwiz#100]
I followed your video step by step, but when I executed your sh-script, I did not get prompted to choose "Internet page" and type in the domain name. Instead it just went straight to the big "Now:" and the domain name it took is from my vps provider OVH, so: "mail._domainkey.vps######.ovh.net" (censored the number).

Do you know how to change that? Even if I change the TXT records to my domain name, thunderbird "fails to find the settings for the email account".

Edit: I just saw that the script had some errors of packages that couldn't be installed. This is what it said:

"""
Installing programs...
Reading package lists... Done
Building dependency tree
Reading state information... Done
postfix is already the newest version (2.11.0-1).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 spamassassin : Depends: libhtml-parser-perl (>= 3.43) but it is not going to be installed
                Depends: libsocket6-perl but it is not going to be installed
                Depends: libwww-perl but it is not going to be installed
                Depends: libnet-dns-perl (>= 0.34) but it is not going to be installed
                Depends: libnetaddr-ip-perl but it is not going to be installed
                Depends: perl-modules (>= 5.10) or
                         libio-zlib-perl (>= 1.04)
E: Unable to correct problems, you have held broken packages.
"""

**Comment by Tancred423** [comment]
It had to be a scuffed file system. I set up a brand new server and it worked fine.
But I still can't access it in Thunderbird. I put in everything like in your video (but with my domain, username and pwd) and it loads for a while like it actually finds the server but then says "Thunderbird failed to find the settings for your email account."

I do have the TXT records.. any ideas?

**Comment by LukeSmithxyz** [comment]
One important note now is that the "username" thing is no longer used.
Just have it log in as your full mail address.

Thunderbird will often autoset some other stuff and sometimes it shows
an error even if you then try again with the same settings and it
magically works. Something with Thunderbird.

**Comment by Tancred423** [comment]
Hey, thanks for the quick help. I solved my issue by not using Cloudflare as my DNS but directly using the DNS settings from DigitalOcean (my new VPS provider) eventhough I had the Cloudflare NS setup correctly... whatever

Tho there is still one problem left:
I can receive and send mails, even to Gmail, but (only tested on Gmail tbh) in Gmail it will be marked as spam.
It indeed says "Standard encryption (TLS)" and the DKIM Test passes (Looks exactly like in your video). 
Gmail is telling me "Why is this message in spam? It is similar to messages that were identified as spam in the past."

Does this mean this is a problem just for my Gmail account? Will I will be marked as spam for other people?

**Comment by LukeSmithxyz** [comment]
If your domain name is new, sometime new domains are automatically spamlisted for a period.

Also, if you are sending little one-line test emails or mail with random text, that will probably be marked as spam as well.

**Comment by Tancred423** [comment]
Mhh, the domain isn't new and it also happens when I try to make a long serious looking text...
Well if the DKIM tests passes, then there's nothing else I can do, is there?
Otherwise, I'll just hope and wait.

Thank you anyway! Was a nice tutorial.

**Comment by nikitalocalhost** [comment]
https://www.digitalocean.com/community/questions/outbound-tcp-port-25-is-blocked
I guess all new DigitalOcean accounts needs to wait 60 days before they can open the port

**Comment by kushagraagent47** [comment]
> Mhh, the domain isn't new and it also happens when I try to make a long serious looking text... Well if the DKIM test passes, then there's nothing else I can do, is there? Otherwise, I'll just hope and wait.
> 
> Thank you anyway! Was a nice tutorial.

Hey you got the issue fixed?

**Comment by Tancred423** [comment]
> > Mhh, the domain isn't new and it also happens when I try to make a long serious looking text... Well if the DKIM test passes, then there's nothing else I can do, is there? Otherwise, I'll just hope and wait.
> > 
> > Thank you anyway! Was a nice tutorial.
> 
> Hey you got the issue fixed?

no i didn't sorry :(
