### ISSUE TITLE
smtp connection timed out

### ISSUE THREAD

**Issue by moorejoshua96** [LukeSmithxyz/emailwiz#103]
I followed the video and was able to install everything.I am able to recieve email just fine but not send email.When i check /var/log/mail.log it shows that the smtp connection has timed out.Any solutions come to mind?Thanks

**Comment by moorejoshua96** [comment]
i would be happy to post the output of the log but should i white out the ip addresses etc? thanks

**Comment by kp9001** [comment]
Have you checked all of the troubleshooting options [here](https://github.com/LukeSmithxyz/emailwiz#troubleshooting----cant-send-mail)?

**Comment by moorejoshua96** [comment]
i am using vultr and have requested that they open port 25.This is the most obvious cause of my error.I apologize and thank you for the help.
