### ISSUE TITLE
~/mail/ is not created, cannot log in with Canary on MacOS

### ISSUE THREAD

**Issue by christopher-kapic** [LukeSmithxyz/emailwiz#104]
I am trying to login with Canary on MacOS, but cannot authenticate. When I SSH into my server and su [user] and check the user's home directory, there is no mail folder. There is also not a mail folder at the root user's home directory.
-Are these problems related?
-What should I do?

**Comment by LukeSmithxyz** [comment]
Is your user a member of the mail group?

**Comment by christopher-kapic** [comment]
Yes. I created two users with the command `useradd -m -G mail billy`.

In case this is helpful, here are the users so far:
```
grep 'mail' /etc/group
mail:x:8:dmarc,cricky,billy
vmail:x:1000:
```

**Comment by LukeSmithxyz** [comment]
Well, I will additionally say that the mail directory will not be created until you receive an email. Only then does dovecot create the folders. Until you add root to the mail group and send a mail there, obviously mail will not appear as a folder there either.

Are you using just the username or the whole email to log in? When I originally made the video on this, you use the username. Now it is the full email address only.

**Comment by christopher-kapic** [comment]
Okay, I'll try sending a mail to the address and then logging in. I'm pretty sure I used the full email when I was logging in before. Thanks Luke!
