### ISSUE TITLE
Does spamassassin use emails sent to Junk as basis for scoring?

### ISSUE THREAD

**Issue by mikeziri** [LukeSmithxyz/emailwiz#107]
Hi,

how does spamassassin work in this configuration?
**moving emails to the junk maildir is what helps SA score future emails?**
also, when emails are detected as spam, are they moved to Junk maildir?

This is my expected behaviour but I'm not sure this is what is happening and if not, could anyone point me in the right direction to configure it that way?

thank you

**Comment by mikeziri** [comment]
I just noticed on /var/log/mail.err that postfix wasn't able to connect to spamd.
systemctl statys spamassassin indicates it wasn't running.
I don't know if it randomly quit.
after systemctl start spamassassin it seems to be running **but my initial question is still valid**

**Comment by LukeSmithxyz** [comment]
Spamassassin does not reread your directories for changes. Moving something to the junk will not by itself change anything. Read the spamassassin documentation or sa-learn for ways to hone its effectiveness or ask on a spamassassin forum/repo.

**Comment by mikeziri** [comment]
in other words, in this installation, spamassassin just uses an internal db with filters to run against incoming email and changes its headers?
