### ISSUE TITLE
Cannot connect to server from FairEmail

### ISSUE THREAD

**Issue by kp9001** [LukeSmithxyz/emailwiz#108]
I appear to be having the same issue as #68 but unlike them, my server is already running Debian 10, so that was not the fix. 

I am able to connect to my email server via neomutt without a problem and send mail. However, when I try to connect with the FairEmail app, I get an error when trying to set up smtp, claiming it could not parse TLS headers. (Note, I am able to connect via imap and receive mail in FairEmail.) When I check journalctl -xe, I see

date/tIme username postfix/submission/smtpd[number]: connect from ip address/ISP[ip address]
date/time username postfix/submission/smtpd[number]: lost connection after CONNECT from ip address/ISP[ip address]
date/time username postfix/submission/smtpd[number]: disconnect from ip address/ISP[ip address] commands=0/0

Curiously, this *was* working in the past. I noticed it when I changed my user password, and attempted to change the password in the app so that it would connect. I tried uninstalling and reinstalling the app, but had the same result. I can't imagine how changing my user password could have caused this. Is that possible? 

Any idea what else I could do to troubleshoot the issue?

**Comment by LukeSmithxyz** [comment]
Is there an option to clean out this program (FairEmail)'s cache or something?
