### ISSUE TITLE
Can't connect to the mail server (errors with the dovecot config)

### ISSUE THREAD

**Issue by monomaani** [LukeSmithxyz/emailwiz#111]
Dec 30 00:38:32 server.com systemd[1]: Starting Dovecot IMAP/POP3 email server...
**Dec 30 00:38:32 server.com dovecot[25342]: doveconf: Fatal: Error in configuration file /etc/dovecot/dovecot.conf line 12: Unknown setting: ssl_min_protocol**
Dec 30 00:38:32 server.com systemd[1]: dovecot.service: Control process exited, code=exited status=89
Dec 30 00:38:32 server.com systemd[1]: Failed to start Dovecot IMAP/POP3 email server.
Dec 30 00:38:32 server.com systemd[1]: dovecot.service: Unit entered failed state.
Dec 30 00:38:32 server.com systemd[1]: dovecot.service: Failed with result 'exit-code'.

Dec 30 00:40:58 server.com systemd[1]: Starting Dovecot IMAP/POP3 email server...
**Dec 30 00:40:58 server.com dovecot[25626]: doveconf: Fatal: Error in configuration file /etc/dovecot/dovecot.conf line 14: ssl_dh: Can't open file /usr/share/dovecot/dh.pem: No such file or directory**
Dec 30 00:40:58 server.com systemd[1]: dovecot.service: Control process exited, code=exited status=89
Dec 30 00:40:58 server.com systemd[1]: Failed to start Dovecot IMAP/POP3 email server.
Dec 30 00:40:58 server.com systemd[1]: dovecot.service: Unit entered failed state.
Dec 30 00:40:58 server.com systemd[1]: dovecot.service: Failed with result 'exit-code'.

Fixed it by just deleting those two lines from the config.

**Comment by 641i130** [comment]
Looks like the SSL certs weren't generated. Check to see if they're on the system with `find / -name "dh.pem" and move them to the right directory. If not, read the script and find the bit that generates the ssl certs go from there.

**Comment by monomaani** [comment]
The tsl encryption works and everything works perfectly after just removing the two lines causing problems.

**Comment by LukeSmithxyz** [comment]
That line is necessary in dovecot 2.3, but won't work on older versions. I recommend keeping the settings and keeping up with recent dovecot versions, but removing it will work.

**Comment by ashishkpaul** [comment]
find and install Dovecot community repositories at https://repo.dovecot.org/
