### ISSUE TITLE
Deprecated options in main.cf

### ISSUE THREAD

**Issue by K1D77A** [LukeSmithxyz/emailwiz#112]
Hi, after running into connectivity issues which I will raise in another issue; I showed my main.cf to the folks in #postfix on freenode where they pointed out that some of the options are deprecated and have been for a long time (10+ years).
see http://www.postfix.org/postconf.5.html#smtpd_tls_security_level specifically the *_use_tls options. 

Thanks.

**Comment by LukeSmithxyz** [comment]
Is `smtpd_use_tls` the only one they mentioned?

**Comment by K1D77A** [comment]
That is the one that was explicitly mentioned but overall I don't think they were very impressed, if you have the time I'd go into the #postfix on freenode and have a chat.
