### ISSUE TITLE
service start error 

### ISSUE THREAD

**Issue by focus85** [LukeSmithxyz/emailwiz#114]
doveconf: Fatal: Error in configuration file /etc/dovecot/dovecot.conf line 10: ssl_cert: Can't open file /etc/dovecot/./fullchain.pem: No such file or directory

any idea/comments are much appreciated.

**Comment by LukeSmithxyz** [comment]
Could you paste here the output of the command `certbot certificates`?

If basically nothing shows up, the issue is because you had not gotten a certificate for SSL before running the wizard.

**Comment by focus85** [comment]
that command returned four different certificates for the four domain I am running on the server. 

Thanks for the help Luke

**Comment by LukeSmithxyz** [comment]
Please post the output (you can feel free to anonymize the domains if
you feel like it).

The script is supposed to use that command to autodetect the
certificates, but there must be something different that showed up in
your command's formatting.

**Comment by focus85** [comment]
certbot certificates
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Found the following certs:
  Certificate Name: XXXX
    Domains: XXXX.tcom www.XXXX.com
    Expiry Date: 2021-02-04 16:37:01+00:00 (VALID: 35 days)
    Certificate Path: /etc/letsencrypt/live/XXXX.com/fullchain.pem
    Private Key Path: /etc/letsencrypt/live/XXXX.com/privkey.pem
  Certificate Name: XXXXXXXX.com
    Domains: XXXX.com www.XXXX.com
    Expiry Date: 2021-03-04 16:01:36+00:00 (VALID: 62 days)
    Certificate Path: /etc/letsencrypt/live/XXXX.com/fullchain.pem
    Private Key Path: /etc/letsencrypt/live/XXXX.com/privkey.pem
  Certificate Name: XXXXX.com
    Domains: XXXXX.com www.XXXXX.com
    Expiry Date: 2021-02-22 05:47:42+00:00 (VALID: 52 days)
    Certificate Path: /etc/letsencrypt/live/XXXXX.com/fullchain.pem
    Private Key Path: /etc/letsencrypt/live/XXXXX.com/privkey.pem
  Certificate Name: XXXXXX.com
    Domains: XXXXXX.com www. XXXXXX.com
    Expiry Date: 2021-02-28 14:43:41+00:00 (VALID: 58 days)
    Certificate Path: /etc/letsencrypt/live/ XXXXXX.com/fullchain.pem
    Private Key Path: /etc/letsencrypt/live/ XXXXXX.com/privkey.pem
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by LukeSmithxyz** [comment]
Okay, thank you. I'll look into why this didn't work for you the first
time and fix it.
