### ISSUE TITLE
Relay Access Denied on attempt to reply to email.

### ISSUE THREAD

**Issue by 641i130** [LukeSmithxyz/emailwiz#115]
I've been trying to fix this error for the past week and I still get this when trying to reply to my email from a different mail server:
`554 5.7.1 <myuser@emailwiz.com>: Relay access denied` Could it be possible gmail blocked my server? It wouldn't make sense because it received the mail but I just reply.

I'm not sure how to go about troubleshooting or fixing this. Please tell me what information you need and I'll post it below.

**Comment by 641i130** [comment]
Update. I'm able to send mail to my server using ``myuser@mail.emailwiz.com`` vs what I was trying before ``myuser@emailwiz.com``. How can I change this so it works either way or just with `emailwiz.com`?

**Comment by LukeSmithxyz** [comment]
Did you accidentally set the input the mail server as `mail.emailwiz.com` instead of `emailwiz.com` when it asked you at the beginning or something? What are the contents of `/etc/mailname`?

**Comment by 641i130** [comment]
`# cat /etc/mailname`
`emailwiz.com` 

And I gave it `emailwiz.com` for the Postfix setup with the input box. My knowledgeable friend told me virtual or local aliases for postfix might fix this but I have yet to try that.

**Comment by LukeSmithxyz** [comment]
Well in that case, I think it's pretty likely you messed something up in your DNS records and `mail.` isn't redirecting your your main domain correctly.

**Comment by 641i130** [comment]
`mail._domainkey.emailwiz.com	TXT	v=DKIM1; k=rsa; p=[REDACTED]
_dmarc.emailwiz.com	TXT	v=DMARC1; p=none; rua=mailto:dmarc@emailwiz.com; fo=1
@	TXT	v=spf1 mx a:mail.emailwiz.com -all`

Anything off here? This is exactly what it generated for me.

**Comment by LukeSmithxyz** [comment]
No, I mean your A/CNAME/MX records.

**Comment by 641i130** [comment]
``
A | emailwiz.com | 1.2.3.4 | 300 
A | irc.emailwiz.com | 1.2.3.4 | 300
CNAME | *.emailwiz.com | emailwiz.com | 300 | 
MX | emailwiz.com | fwd1.porkbun.com | 300 | 10 |
MX | emailwiz.com | fwd2.porkbun.com | 300 | 20 | 
``
Anything off with this? Maybe I'm missing `mail.emailwiz.com` ?

**Comment by LukeSmithxyz** [comment]
Yeah. Put in an A record for mail just in case. I would think the CNAME wildcard would take are of that, but maybe your registrar doesn't accept wildcard redirects?

**Comment by LukeSmithxyz** [comment]
Wait, wait... What are those MX records for? Some older email setup? They should be directing to `mail.emailwiz.com`.

**Comment by 641i130** [comment]
THAT FIXED IT THANK YOU!!! Thanks for all the inspiring videos too! I don't think I would've made the switch to arch if it wasn't for your videos that show the power of Linux.
