### ISSUE TITLE
Dovecot will not start

### ISSUE THREAD

**Issue by fr0zrr** [LukeSmithxyz/emailwiz#122]
Dovecot will not start no matter what. It keeps throwing up "Can't open file /usr/share/dovecot/dh.pem: No such file or directory" (which I've seen you talked to someone about 22 days ago, but closed the issue a few days later. Any ideas?

**Comment by LukeSmithxyz** [comment]
Update to the most recent version of dovecot or remove the line from the
config.

Honestly, while the 2.3 manual talks about it as if it's required, 2.3
seems to work fine without it, so I might just remove it from the script
altogether since it's causing so many people problems.

**Comment by fr0zrr** [comment]
I did solve it in the end but only by going with Debian over Ubuntu. I initially picked Ubuntu due to experience with it.
