### ISSUE TITLE
Arch support

### ISSUE THREAD

**Issue by toto112358** [LukeSmithxyz/emailwiz#123]
Add support for arch !

**Comment by LukeSmithxyz** [comment]
No u.

**Comment by toto112358** [comment]
I will add support for arch linux then!!!

**Comment by binex-dsk** [comment]
@toto112358 arch version when

**Comment by maddingl** [comment]
@toto112358 Yeah, I would love that, too!!! Do it!

**Comment by toto112358** [comment]
@maddingl @binex-dsk In about two monthes since I am pretty busy with my studies. I'd make [it](https://github.com/toto112358/pypack-repo) in python3 since I am not a bash god lmao.

**Comment by maddingl** [comment]
Nice, thanks :) Good luck with your studies!

**Comment by MGislv** [comment]
While I was setting up my mail server I found the time to modify this script for arch.
It's definetly untested as I fixed most problems on the server first and later touched up the script.
Here it is https://git.ceppo.xyz/MGislv/emailwiz-arch
