### ISSUE TITLE
DKIM-Result permerror (no key)

### ISSUE THREAD

**Issue by RisuSofos** [LukeSmithxyz/emailwiz#125]
When I run a test with [DKIM test](https://appmaildev.com/en/dkim), it outputs the following:
![image](https://user-images.githubusercontent.com/57734346/106083284-d73ded00-60e1-11eb-8c4b-9a421d72dc86.png)
Gmail accounts can not send an email here either. 

Registered with [namecheap](https://www.namecheap.com)
The server is using Debian 10

**Comment by LukeSmithxyz** [comment]
What shows with `systemctl status opendkim`?

**Comment by RisuSofos** [comment]
It says it is loaded and running but can not open PID file
![image](https://user-images.githubusercontent.com/57734346/106160025-0472b580-614b-11eb-8617-cfcd8aedfab6.png)

**Comment by RisuSofos** [comment]
Not sure how I did it but it kinda fixed itself
