### ISSUE TITLE
dmarc report - <spf>fail</spf>

### ISSUE THREAD

**Issue by paapereira** [LukeSmithxyz/emailwiz#132]
Hi there,

I'm having a `<spf>fail</spf>` in a dmarc report.
```
      <policy_evaluated>
        <disposition>none</disposition>
        <dkim>pass</dkim>
        <spf>fail</spf>
      </policy_evaluated>
```
Also checked in https://www.appmaildev.com/en/dkim

```
Query TEXT record from DNS server for: mydomain.xyz

No matched SPF text record found.
```

I had in my DNS, as per the emailwiz output:
`v=spf1 mx a:mail.mydomain.xyz -all`

Am I doing something wrong? I'm sending mails from me@mydomain.xyz and not me@mail.mydomain.xyz
Should I had `v=spf1 mx a:mydomain.xyz -all` instead?

**Comment by Antiquis** [comment]
https://www.spf-record.com/generator

**Comment by paapereira** [comment]
After messing around I got it working using `v=spf1 a mx ~all`.
