### ISSUE TITLE
email address starting with mail@doman.tld

### ISSUE THREAD

**Issue by ghost** [LukeSmithxyz/emailwiz#134]
Hi, would it be possible to create a mail account starting with mail@domain.tld?
If I have seen, the script has hardcoded the term "mail"

**Comment by lukaskretzschmer** [comment]
Yes, just create the "mail" user as explained in the instructions and it will work just fine.

**Comment by lukaskretzschmer** [comment]
> Hi, would it be possible to create a mail account starting with [mail@domain.tld](mailto:mail@domain.tld)?
> If I have seen, the script has hardcoded the term "mail"

Yes, just create a "mail" user as explained in the instructions and it will work just fine.

**Comment by pillepalle1** [comment]
You can also simply follow this:

http://www.postfix.org/VIRTUAL_README.html

to create an alias mail@domain.tld to your own mail. Basically you just create an alias file with `vim /etc/postfix/virtual` and run `postmap /etc/postfix/virtual && postfix reload`

**Comment by lilweege** [comment]
> > Hi, would it be possible to create a mail account starting with [mail@domain.tld](mailto:mail@domain.tld)?
> > If I have seen, the script has hardcoded the term "mail"
> 
> Yes, just create a "mail" user as explained in the instructions and it will work just fine.

You typically can't create a user with the same name as a group, useradd will tell you `user 'mail' already exists`.  

<br>

> You can also simply follow this:
> 
> http://www.postfix.org/VIRTUAL_README.html
> 
> to create an alias [mail@domain.tld](mailto:mail@domain.tld) to your own mail. Basically you just create an alias file with `vim /etc/postfix/virtual` and run `postmap /etc/postfix/virtual && postfix reload`

A note is made to `NEVER list a virtual alias domain name as a mydestination domain!`, which conflicts with existing options. You may have to modify `/etc/postfix/main.cf`. The following is what worked for me:

<br>

Find and repalce myorigin and mydestination, then add virtual options
`vim /etc/postfix/main.cf`
```
# myorigin = /etc/mailname
myorigin = localhost

# mydestination = $myhostname, domain.tld, machinename, localhost.localdomain, localhost
mydestination = machinename, localhost.localdomain, localhost

virtual_alias_domains = domain.tld, mail.domain.tld
virtual_alias_maps = hash:/etc/postfix/virtual
```
Now the domain.tld is a 'hosted domain' which looks for aliases in `/etc/postfix/virtual.db`

Create the virtual file for your aliases
`vim /etc/postfix/virtual`
```
# redirect 'mail' to unix user chad
mail@domain.tld        chad

# all other users should be added back since main.cf changed
billy@domain.tld       billy

# optional catch-all (anything@domain.tld will go to chad)
# @domain.tld          chad
```

'Compile' virtual.db by running
`postmap /etc/postfix/virtual`

Reload server by running
`postfix reload`

**Comment by bh-e** [comment]
> # redirect 'mail' to unix user chad
> mail@domain.tld        chad

But with this approach we be polling imap as chad@domain.tld, right.

**Comment by bh-e** [comment]
> You can also simply follow this:
> 
> http://www.postfix.org/VIRTUAL_README.html
> 
> to create an alias [mail@domain.tld](mailto:mail@domain.tld) to your own mail. Basically you just create an alias file with `vim /etc/postfix/virtual` and run `postmap /etc/postfix/virtual && postfix reload`

Is it same as having 
`mail          chad ` 

in /etc/aliases. Does it also need to change `mydestination` and `myorigin` field ?

**Comment by pillepalle1** [comment]
> > You can also simply follow this:
> > http://www.postfix.org/VIRTUAL_README.html
> > to create an alias [mail@domain.tld](mailto:mail@domain.tld) to your own mail. Basically you just create an alias file with `vim /etc/postfix/virtual` and run `postmap /etc/postfix/virtual && postfix reload`
> 
> Is it same as having
> `mail chad `
> 
> in /etc/aliases. Does it also need to change `mydestination` and `myorigin` field ?

I simply installed the mail server using the script, edited the virtuals-file and run the two commands. Nothing changed in the configuration. Apparently I am not supposed to do that, but it works fine for me.
