### ISSUE TITLE
NOTICE : DKIM signing may fail when sending from mail.yourdomain.tld

### ISSUE THREAD

**Issue by saloniamatteo** [LukeSmithxyz/emailwiz#137]
My website, hosted using GitHub pages at `saloniamatteo.top`, cannot send emails. Thus, by self-hosting my website, I have other domains that point to my server's IP (like the `git` server, `mail` server, etc.)

So, when you send emails from `mail.yourdomain.tld`, make sure that `/etc/postfix/dkim/signingtable` contains `*@mail.yourdomain.tld`, and not `*@yourdomain.tld` (in my case, that would be `*@mail.saloniamatteo.top`)

Also, I think that you have to add `mail.yourdomain.tld` to `/etc/postfix/dkim/trustedhosts`.

I was wondering why DKIM would fail, but now it works, and outbound emails are signed automatically.

**Comment by sermk** [comment]
I second that. Had had problems with DKIM until I followed these instruction. @saloniamatteo Thanks a lot!
@LukeSmithxyz Luke, this should be added to the tutorial on landchad
