### ISSUE TITLE
2048 bit DKIM key is too large for some domain name registars (e.g. Hover)

### ISSUE THREAD

**Issue by shiitake** [LukeSmithxyz/emailwiz#139]
I use Hover as my registrar and I had problems when attempting to add the DKIM key to my DNS settings because the rsa key was greater than 255 characters.  I don't plan on changing registrars but I have reached out to support to make sure they are aware of this limitation.  

As a workaround I went through @LukeSmithxyz 's script and re-generated the DKIM entries with 1024 bit. 

Here are the steps I took: 

1. Since I wasn't rerunning the entire script I ended up setting some of the variables manually
    `domain="$(cat /etc/mailname)"`
    `subdom=${MAIL_SUBDOM: -mail}`
    `maildomain="$subdom.$domain"`
2. Rename the original entries
    `cp /etc/postfix/dkim/mail.txt /etc/postfix/dkim/2048mail.txt`
    `cp /etc/postfix/dkim/mail.private /etc/postfix/dkim/2048mail.private`
3. Generate the new keys using the **-b 1024** flag
    `opendkim-genkey -D /etc/postfix/dkim/ -b 1024 -d $domain -s $subdom`
4. Verify the permissions are still good 
    `chgrp opendkim /etc/postfix/dkim/*`
    `chmod g+r /etc/postfix/dkim/*`
5. Regenerated **dns_emailwizard** file
    `pval="$(tr -d "\n" </etc/postfix/dkim/$subdom.txt | sed "s/k=rsa.* \"p=/k=rsa; p=/;s/\"\s*\"//;s/\"\s*).*//" | grep -o "p=.*")"`
    `dkimentry="$subdom._domainkey.$domain	TXT	v=DKIM1; k=rsa; $pval"`
    `dmarcentry="_dmarc.$domain	TXT	v=DMARC1; p=reject; rua=mailto:dmarc@$domain; fo=1"`
    `spfentry="@	TXT	v=spf1 mx a:$maildomain -all"`
    ```
    echo #$dkimentry
    $dmarcentry
    $spfentry" > "$HOME/dns_emailwizard_UPDATE"
    ```
6. Then restart the `spamassassin`, `opendkim`, `dovecot` and `postfix` services. 

I hope this helps someone.

**Comment by afallon02** [comment]
Nice thanks! Would be cool to add an uninstall script to purge all the entries this script creates then adding a flag when running the script to pass in the bit size for the DKIM key as many registrars are incredibly dumb in how they treat long records; hover for example doesn't support key flattening at all.

**Comment by afallon02** [comment]
Also - you've got a typo in your comment the `domain="$(cas /etc/mailname)"` should be `domain="$(cat /etc/mailname)"`

**Comment by shiitake** [comment]
I corrected the spelling in the original post.  Thanks for the heads up @afallon02 🙏

**Comment by LukeSmithxyz** [comment]
Ok. If other people run into this problem, it's a good idea to contact your registrars with a ticket to fix this issue. It's a registrar problem.

**Comment by koobs** [comment]
For future readers, [Hover hasn't fixed their 1028-bit DKIM record size limitation](https://twitter.com/koobs/status/970246569797681152) since reported in 2018 and doesn't appear intent to do so.

**Comment by Gtoyos** [comment]
This is not necessarly a problem with the DNS provider but with the fact that each TXT record line can have at most 255 characters. What you can do is split the DKIM key in many lines. In AWS Lightsail you can do this just by splitting with newlines.
[For route53 see this post](https://repost.aws/knowledge-center/route53-resolve-dkim-text-record-error)
