### ISSUE TITLE
mail CNAME

### ISSUE THREAD

**Issue by Speedy905** [LukeSmithxyz/emailwiz#140]
Hello,

It might just be my configuration, but if I add a mail CNAME and check it with intodns, I get errors in the MX table, stating that the mail subdomain shouldn't have a CNAME. 

I know that the README states that you need to have a CNAME for the mail subdomain, but I'm wondering if that's what's expected.

![image](https://user-images.githubusercontent.com/33104169/114277382-ee119180-99f8-11eb-8ebd-825cffeac6f1.png)

Note: If I don't have the CNAME entry, I won't able to connect to it from my thunderbird client.

**Comment by Speedy905** [comment]
Hello, figured out what my issue was, I used a different subdomain when connecting to the email server, and no more issues arose.

**Comment by SlidingHorn** [comment]
@Speedy905 Could you clarify what you meant here? I have the same issue, and I'm wondering how to resolve it.

1. Do you still have the CNAME for the `mail.` subdomain?
2. What does your MX record point to now?
3. What did you end up using for your client configuration to be able to connect?

Thanks in advance!

**Comment by Speedy905** [comment]
> @Speedy905 Could you clarify what you meant here? I have the same issue, and I'm wondering how to resolve it.
> 
> 1. Do you still have the CNAME for the `mail.` subdomain?
> 2. What does your MX record point to now?
> 3. What did you end up using for your client configuration to be able to connect?
> 
> Thanks in advance!

So essentially, your MX and CNAME record should be different. For instance, my MX record is `mail.sp33dyboi.xyz` while my CNAME record is `customemail.sp33dyboi.xyz`

![Selection_001](https://user-images.githubusercontent.com/33104169/128574673-0fe6254b-ee03-43c7-9aa7-29c6446cf370.png)

Essentially, for client configuration, you will use your CNAME record for your IMAP and SMTP settings:
![image](https://user-images.githubusercontent.com/33104169/128575074-0d249201-561e-4977-882b-ef9984b234a8.png)
At least that's how it supposed to be. This can send emails to the big ones, but now for some reason it can't receive emails back from them. (Although, internal emails can send/receive within each other). I'm not really keen on trying to figure out this issue, since I mainly use this as a simple smtp server so that services that I use (Unraid for instance) can send email to individuals.
