### ISSUE TITLE
unable sending to gmail or hotmail

### ISSUE THREAD

**Issue by abdellatif-dev** [LukeSmithxyz/emailwiz#142]
unable sending to gmail or hotmail emails 
i've the tried it on 2 instances of vultr depian severs
i recieve emails but i can't send or reply
INFO:
i use neomutt as my email client

**Comment by pillepalle1** [comment]
I had the same issue. At the end of 

https://github.com/LukeSmithxyz/emailwiz/blob/master/README.md

you can find the advice to 

> Ensure that port 25 is open on your server. Vultr for instance blocks this by default, you need to open a support ticket with them to open it. You can't send mail if 25 is blocked

After opening a ticket and explaining thoroughly what sort of mails you are going to send, they unblock your instances and you are free to send mail. Works like a charm

**Comment by pillepalle1** [comment]
Actually vultr also provides these information here

https://www.vultr.com/docs/what-ports-are-blocked

**Comment by abdellatif-dev** [comment]
thank you i just opened a ticker to unblock post 25

**Comment by afallon02** [comment]
This sounds like a feature, not a bug.

**Comment by abdellatif-dev** [comment]
Thanks again
