### ISSUE TITLE
Unable to log in with thunderbird (Can't connect to dovecot?)

### ISSUE THREAD

**Issue by Xenorio** [LukeSmithxyz/emailwiz#145]
Trying to set up a mailserver for my website so i can actually reply to mails with an address on my domain (Until now i just set my DNS settings to forward everything to a gmail address)

After running this script, i have only changed the paths for my SSL cert and key in the configs for postfix and dovecot (And restarted both of course)

Now, i want to connect to it with thunderbird. I have edited the settings to what the readme says, but thunderbird tells me it can't log in: 
![Thunderbird Settings](https://i.imgur.com/lSdjciV.png)

I have checked journalctl for any errors, but there are none. On the other hand, it's not telling me anything about an attempted connection either. 

I am able to connect to postfix through telnet on port 587 and also 25. But connections to port 983 for dovecot get refused!
![Trying telnet](https://user-images.githubusercontent.com/39472201/121630284-2414d580-ca7d-11eb-9dac-b0f305b7d677.png)

The dovecot service is active tho
![Dovecot service status](https://user-images.githubusercontent.com/39472201/121631103-bff31100-ca7e-11eb-8d66-173ff5757220.png)

Of course, all relevant ports are being forwarded to the server. There's no additional firewall other than that of my router that could be blocking things.

On the DNS side of things, mail.xenorio.xyz is properly pointing to the correct network. I have also set up the DKIM and DMARC records, but no MX records yet (I want to be able to still receive mails while i'm working on this, so i wanna update MX when everything else works)

I am not using any hosting provider. Everything is running on a machine in my local network. 

My configs:
| Postfix main.cfg | Dovecot dovecot.conf |
| :-------------------: | :---------------------------: |
| https://paste.ubuntu.com/p/PBPfhZzd4W/ | https://paste.ubuntu.com/p/mbkcZsR757/ |

Also, have a neofetch:
![Neofetch Output](https://i.imgur.com/8rvVn1H.png)

**Comment by Antiquis** [comment]
The standard IMAP port is `993`, not `983`.

Additionally, if you continue to have problems, try the following:
- Connect directly to the IP address of the server, not via DNS - this will allow you to figure out whether this is a DNS-related problem, or something else;
- Use nmap to see if the port is open. Do this firstly on another computer on your network - if you have no luck there, try on the machine itself.

If none of the above work for you, please can you provide the Dovecot log (**make sure to redact any sensitive info**).

**Comment by Xenorio** [comment]
oh my god yeah, seems like i misread the IMAP port in the readme. i'm successfully logged in now. sorry for the trouble, and thanks for the help!
