### ISSUE TITLE
Not able to send email but able to receive email 

### ISSUE THREAD

**Issue by theutkarshjaiswal** [LukeSmithxyz/emailwiz#148]
I am using ubuntu 20.4
Google cloud 
enabled firewall and added these tcp ports 25,2525,587,143,110,995,80,443,993
I run this command journalctl -xe

-- Subject: A start job for unit UNIT has finished successfully
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- A start job for unit UNIT has finished successfully.
-- 
-- The job identifier is 5.
Jul 03 15:27:54 brokeio systemd[1993]: Reached target Basic System.
-- Subject: A start job for unit UNIT has finished successfully
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- A start job for unit UNIT has finished successfully.
-- 
-- The job identifier is 2.
Jul 03 15:27:54 brokeio systemd[1]: Started User Manager for UID 1001.
-- Subject: A start job for unit user@1001.service has finished successfully
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- A start job for unit user@1001.service has finished successfully.
-- 
-- The job identifier is 889.
Jul 03 15:27:54 brokeio systemd[1]: Started Session 4 of user brokeio_com.
-- Subject: A start job for unit session-4.scope has finished successfully
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- A start job for unit session-4.scope has finished successfully.
-- 
-- The job identifier is 969.
Jul 03 15:27:54 brokeio systemd[1993]: Reached target Main User Target.
-- Subject: A start job for unit UNIT has finished successfully
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- A start job for unit UNIT has finished successfully.
-- 
-- The job identifier is 1.
Jul 03 15:27:54 brokeio systemd[1993]: Startup finished in 69ms.
-- Subject: User manager start-up is now complete
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The user manager instance for user 1001 has been started. All services queued
-- for starting have been started. Note that other services might still be starting
-- up or be started at any later time.
-- 
-- Startup of the manager took 69834 microseconds.
Jul 03 15:28:03 brokeio sudo[2083]: brokeio_com : TTY=pts/0 ; PWD=/home/brokeio_com ; USER=root ; COMMAND=/bin/bash
Jul 03 15:28:03 brokeio sudo[2083]: pam_unix(sudo:session): session opened for user root by brokeio_com(uid=0)
lines 3184-3234/3234 (END)

**Comment by r1bnc** [comment]
Not enough info, maybe try to reset your installation?
