### ISSUE TITLE
renewed ssl certs, can't send/recv mail

### ISSUE THREAD

**Issue by DevHyperCoder** [LukeSmithxyz/emailwiz#149]
Hey, i have been using this for a month now. my lets encrypt certs were renewed a few days back. now, im not able to connect to the mail server.

```
SSL error connecting mail.example.com (blah.blah.blah.blah:993): certificate has expired
```

Please tell me what info you require ?

Thanks

**Comment by LukeSmithxyz** [comment]
If certbot renewed your certs automatically, it may have bundled them differently and thus it might be in a different file location. You would have to change the referred to location in the dovecot/postifx config files in that case.

**Comment by shiitake** [comment]
@DevHyperCoder I had the exact same issue and I was able to resolve it by logging into the server and reloading postfix and dovecot. 

To mitigate this going forward I've created a shell script to do this automatically whenever the certificate is renewed.  Just run the following commands to create the script. 

```
sudo sh -c 'printf "#!/bin/sh\nsystemctl reload postfix\nsystemctl reload dovecot\n" > /etc/letsencrypt/renewal-hooks/post/reload.sh'
sudo chmod 755 /etc/letsencrypt/renewal-hooks/post/reload.sh
```

**Comment by DevHyperCoder** [comment]
@LukeSmithxyz @shiitake Thanks a lot. I restarted postfix and dovecot and it fixed it. Didn't think of that before.

Thanks
