### ISSUE TITLE
Issue when migrating to new server with Vultr snapshots

### ISSUE THREAD

**Issue by rkb97** [LukeSmithxyz/emailwiz#150]
Hello,

I had the email server up and everything was working, but I needed to upgrade my server on Vultr (need more memory for chat/video call server). I used the snapshot feature they provide to backup and deploy to a larger VPS. Everything else I had installed came back and worked right away, but still having trouble with getting email back online. I updated the A & AAAA DNS and reverse DNS records with the new IP, I tried restarting dovecot/postfix. Do the TXT records need to be changed also? Should I just run the script again on new VPS or is there anything else I should try first?

When trying to send email, neomutt gives this error message after a few minutes:
```
msmtp: cannot connect to mail.example.xyz, port 587: Connection timed out
msmtp: could not send mail (account user@example.xyz from
/home/user/.config/msmtp/config)
```

I tried logging in with Thunderbird also to see if it's client-side neomutt issue but couldn't connect. Email was working perfect before snapshot and migrating to new server, so I'm sure there's just a step I'm missing when migrating. Is there anything in the config files that needs to be changed when migrating servers? I've read issue #106 and issue #36 but they're different to my problem regarding Vultr snapshots.

Thanks for any help.

**Comment by LukeSmithxyz** [comment]
- Open a ticket with Vultr to ensure that they are not blocking your mail ports, which they do by default.
- Disable `ufw`, which also now comes installed by default, or at least enable mail capabilities.

Also on Vultr, you do not need to remake a VPS to upgrade to higher RAM/CPU. You can choose to change the plan without wiping your server.

**Comment by rkb97** [comment]
Thank you! Fixed it with ufw allow on ports 25, 587, and 993. I thought the ufw settings would carry over with the snapshot but guess not, I actually don't even remember doing it on these ports the first time just the 80 and 443 ports I had on. I had Vultr unblock the mail ports already and have done a few server installs since then, should only have to do that once for your whole account it seems.

Thanks for the tip, I see change plan under settings now... I'm still new at this. Snapshots were just more noticeable on the front page lol.
