### ISSUE TITLE
Allow users to change their own password?

### ISSUE THREAD

**Issue by SlidingHorn** [LukeSmithxyz/emailwiz#152]
I've set up a mailserver where I intend to set up accounts for some family members, close friends, etc., but I just realized that as it stands, I would have to set their passwords for them and be the one to change it for them if needed.

Is there a way to have them be able to do this themselves (without having to log into a remote server via ssh, etc? These are not exactly "tech" people, and I don't want to know/handle their passwords.

**Comment by LukeSmithxyz** [comment]
You would have to write a little PHP page or something where they could create accounts or reset their passwords.

This is sort of beyond the purview of this repo to be honesty, you'll have to learn how to make a little web interface for that.

I was thinking about changing this repo from using user accounts/PAM to using a database to store logins. This might sort of make the process easier maybe safer.
