### ISSUE TITLE
Cant receive mail

### ISSUE THREAD

**Issue by ghost** [LukeSmithxyz/emailwiz#153]
I can send mail but when I try to send mail to the account I get the error:

DNS Error: 25805260 DNS type 'mx' lookup of domain.com responded with code NOERROR 25805260 DNS type 'mx' lookup of domain.com had no relevant answers. 25805260 DNS type 'aaaa' lookup of domain.com responded with code NOERROR 25805260 DNS type 'aaaa' lookup of domain.com had no relevant answers. 25805260 DNS type 'a' lookup of domain.com responded with code NOERROR 25805260 DNS type 'a' lookup of domain.com had no relevant answers.

**Comment by cptchuckles** [comment]
Can you export your entire DNS zone so we can see what records you have?  It sounds like your DNS MX record is not set up correctly, or does not exist
