### ISSUE TITLE
mail.log flooded with dovecot error

### ISSUE THREAD

**Issue by SlidingHorn** [LukeSmithxyz/emailwiz#155]
I've had this error flooding my mail logs ever since I set up the mailserver, and now that I'm seemingly not getting any incoming messages, I figured it was time to find out wth it means and how to get rid of it:

```
Jul 29 00:57:13 vmi629291 dovecot: lda(root)<3998><UY5JL8ngAWGeDwAAZy+t8g>: Error: stat(/root/Mail/Inbox/tmp) failed: Permission denied (euid=65534(nobody) egid=65534(nogroup) missing +x perm: /root, dir owned by 0:0 mode=0700)
Jul 29 00:57:13 vmi629291 dovecot: lda(root)<3998><UY5JL8ngAWGeDwAAZy+t8g>: Error: sieve: msgid=<20210728223713.5A58B8A0DC9@mail.mydomain.xyz>: failed to store into mailbox 'INBOX': Internal error occurred. Refer to server log for more information. [2021-07-29 00:57:13]
Jul 29 00:57:13 vmi629291 dovecot: lda(root)<3998><UY5JL8ngAWGeDwAAZy+t8g>: Error: sieve: Execution of script /var/lib/dovecot/sieve/default.sieve was aborted due to temporary failure
Jul 29 00:57:13 vmi629291 postfix/local[3997]: 5A58B8A0DC9: to=<root@mydomain.xyz>, orig_to=<root>, relay=local, delay=1205, delays=1205/0.02/0/0.03, dsn=4.3.0, status=deferred (temporary failure. Command output: lda(root): Error: net_connect_unix(/var/run/dovecot/stats-writer) failed: Permission denied )
```

There's an entry like this about every ten minutes...

I originally looked into this because a friend tried to send me an email, and I didn't get it. I looked in `mail.log` and there's no indication of that email whatsoever.

I attempted to send an email from my gmail account (I know...I'm slowly getting rid of it), and saw this:

```
830 Jul 29 00:39:59 vmi629291 postfix/smtp[1824]: B5AF68A0DC6: to=<mygmailaddress@gmail.com>, relay=gmail-smtp-in.l.google.com[142.250.110.27]:25, delay=1.6, delays=0.42/0.01/0.18/0.95, dsn=2.0.0, status=sent (250 2.0.0 OK  1627511999 u17si1033548wri.59 - gsmtp)
831 Jul 29 00:39:59 vmi629291 postfix/qmgr[1597]: B5AF68A0DC6: removed
```

I'm assuming `removed` means it just deleted the message? If so, why?

Thanks in advance for any help here...

**Comment by DimitrijeDobrota** [comment]
`Error: stat(/root/Mail/Inbox/tmp) failed: Permission denied (euid=65534(nobody) egid=65534(nogroup) missing +x perm: /root, dir owned by 0:0 mode=0700)`

It seems like you are trying to receive mail to root@yourdomain which is not a good idea security wise.

I suggest you make another user, add it to mail group, and add alias that redirects root@yourdomain to new-user@yourdomain if you desire.

**Comment by SlidingHorn** [comment]
I never created a root mail account. I have one for my first name, and that's it...

**Comment by SlidingHorn** [comment]
So what seems to have happened is that my "mysterious" lack of incoming mail happened to coincide with my first reboot after installing and configuring `ufw`.  Made sure the right ports were opened, rebooted, and I'm receiving mail.

Still curious as to who's trying to send mail to  `root` though

**Comment by LukeSmithxyz** [comment]
At any given time, there are going to be hundred of Chinese machines trying to variously hack or spam your server. That's just how it is. You're just getting phising mails and ads at the root account.
