### ISSUE TITLE
[suggestion] Add webmail.

### ISSUE THREAD

**Issue by danielfan61a** [LukeSmithxyz/emailwiz#156]
[Rainloop](https://www.rainloop.net/) seems like a good project to integrate with emailwiz as you're not always home near your ThinkPad to access your e-mails from your minimalist ncurses mutt wizard program. 

Having a webmail would be a nice addition to this project. 

I have no idea how to set this up. Can someone help with this? if you think it is a good idea that is.

**Comment by LukeSmithxyz** [comment]
I do know someone who has set this up, and I would sort of like to add a guide to it on https://landchad.net.

As for this project though, I certainly do not want it in here by default. Maybe as time passing and I make some other changes, I might draft up an option to add something like this, but not now.

There are other backend changes I would need to implement this as well, I believe. The user authentication with this script is done via PAM and creating Unix users on the server. I'm pretty sure rainloop and most other services like this will require a database and such. For other reasons I might change to that, but I will cross that bridge when I get there.

**Comment by danielfan61a** [comment]
That is understandable. A guide on https://landchad.net would certainly be better as a webmail is optional and not necessary to have a mail server.

> I'm pretty sure rainloop and most other services like this will require a database and such

On the website, it says:
"Modest system requirements, decent performance, simple installation and upgrade,
**no database required** - all these make RainLoop Webmail a perfect choice for your email solution."

So I don't think it uses a database and instead uses regular Unix users.

**Comment by danielfan61a** [comment]
I recently installed rainloop on my server, it was very easy and everyone should get it. just follow [this tutorial](https://www.linuxbabe.com/mail-server/install-rainloop-webmail-ubuntu-20-04). it is a super basic webmail that gets the job done. **no db** required, the only dependencies are: Nginx and PHP7.

would love to see it on https://landchad.net. @LukeSmithxyz
