### ISSUE TITLE
CentOS

### ISSUE THREAD

**Issue by mectorfector** [LukeSmithxyz/emailwiz#171]
Would you be interested in converting your script to work on CentOS aswell as Debian?

**Comment by r1bnc** [comment]
This script is made for Debian.

**Comment by summersalt9** [comment]
> I converted it myself, if anyone is interested

I am interested bro.. pls can you share with me now?

**Comment by ThamognyaKodi** [comment]
@mectorfector Could you please make a git repo or find a way to share it. I think it might be helpful for a lot people who use centos.

**Comment by denisapain** [comment]
please
