### ISSUE TITLE
Doesn't work on Debian 11?

### ISSUE THREAD

**Issue by inezserrano** [LukeSmithxyz/emailwiz#174]
I followed his video completely, but when I try to access the email accounts I've created using Thunderbird, I can't. I'm using the correct email and password, I have the correct manual configuration as he shows it in his video. 

One issue maybe be that my domain provider lables things differently. In his guide he fills out a "points to" box, my domain provider doesn't have that, the options are called "name" and "content" instead. If I filled this out wrong, that might be my issue. 

Another interesting thing is that certbot fails to set up for mail.mysite.com and www.mail.mysite.com, so maybe that's part of the problem?

**Comment by inezserrano** [comment]
There is 100% packet loss when I ping port 993 or 587.

**Comment by r1bnc** [comment]
Check if your provider blocks those ports.

**Comment by Theory-of-Everything** [comment]
To bounce off @r1bnc, you will want to first check if your vps provider blocks email ports (933, 587, 25, 465). If you have these ports unblocked and you still have issues connecting, check to make sure that your firewall is not blocking these ports.

Note that many vps providers provide their own firewall implementation (for instance, vultr has a firewall configuration tool for every instance you run. This is separate to an internal tool (such as `ufw`).

If you want to use something like `ufw` make sure that your firewall provided by your vps is turned off, and that you have allowed those ports to receive connections.

**Comment by r1bnc** [comment]
> To bounce off @r1bnc, you will want to first check if your vps provider blocks email ports (933, 587, 25, 465). If you have these ports unblocked and you still have issues connecting, check to make sure that your firewall is not blocking these ports.
> 
> Note that many vps providers provide their own firewall implementation (for instance, vultr has a firewall configuration tool for every instance you run. This is separate to an internal tool (such as `ufw`).
> 
> If you want to use something like `ufw` make sure that your firewall provided by your vps is turned off, and that you have allowed those ports to receive connections.

It doesn't its just gmail blocking. Not resolved as of this moment. Gave up on it
