### ISSUE TITLE
Manage multiple domains

### ISSUE THREAD

**Issue by ghost** [LukeSmithxyz/emailwiz#175]
Hi, i installed and configured the mail server with my domain. Now i would like to add another domain and manage it, is there any guide on how to do this?

**Comment by dedelkv** [comment]
I would like to know, also.

**Comment by adrientremblay** [comment]
@Alphvino @dedelkv 

Check out http://techslides.com/mail-server-for-multiple-domains-with-postfix. Worked for me

Also there are three other issues regarding this. Just search for 'multiple domain' and you'll find them.

**Comment by Alphvino** [comment]
> @Alphvino @dedelkv
> 
> Check out http://techslides.com/mail-server-for-multiple-domains-with-postfix. Worked for me
> 
> Also there are three other issues regarding this. Just search for 'multiple domain' and you'll find them.

alright, thanks!
