### ISSUE TITLE
Postfix configuration leaks IP addresses

### ISSUE THREAD

**Issue by thomasoll** [LukeSmithxyz/emailwiz#178]
As it stands, the configuration (which is excellent by the way) leaks the source ip of the sender.
Recommend you amend the following files to strip the "Received From:" section of this:

add to /etc/postfix/main.cf
`header_checks = regexp:/etc/postfix/header_checks`

create file /etc/postfix/header_checks and add:
```

/^Received:.*/     IGNORE
/^X-Originating-IP:/    IGNORE

```

**Comment by Fijxu** [comment]
I also changed these settings months ago after I realized that the headers of the emails I was sending were leaking my external ip.
It would be good for privacy if by default the configuration would not read the external ip of the sender.

**Comment by programmer-ke** [comment]
Not an expert, but I spent some time looking into this. Just in-case in may not be obvious to anyone looking at this, the headers will be stripped for *both* incoming and outgoing emails.

Most may not care about this, but if you only want to strip the sending client's headers, see this for a possible solution: https://serverfault.com/a/998993
