### ISSUE TITLE
Changing domains and reinstalling emailwiz without getting into spam

### ISSUE THREAD

**Issue by JPcode05** [LukeSmithxyz/emailwiz#185]
Can I change domains for my email server, including the rDNS, certificate, and reinstall emailwiz while updating SPF, DKIM and DMARC configurations, and still not get into spam? I am switching domains and I'm worried that if I switch I will be sent into spam, which I'm not currently.

And how do I uninstall and reinstall emailwiz? Do I have to purge any files?

EDIT: Also, I want to add a subdomain to my server (*box*.example.org). Can emailwix have an option for subdomains, as long as you point CNAMES (example.org, www.example.org, mail.example.org) back to that name? (The MX record in this case will point to box.example.org because it cannot point to a CNAME.)

**Comment by r1bnc** [comment]
For migrating here is what I did:
1. Stopped the mail server
2. Copied /home/<user>/Mail directories to the new server
3. Install emailwiz to the new server
4. Changed SPF, DKIM, DMARC to the new emailwiz generated config on my provider DNS
5. Add email users, set permissions (chown/chmod) on the new server
6. Restart the new mail server
7. Test email
8. Run uninstall script on the old mail server.
9. Done

For the subdomain not sure. IIRC we need to use the root domain for the email.

**Comment by JPcode05** [comment]
> For the subdomain not sure. IIRC we need to use the root domain for the email.

Then I'll use the root domain, until Luke Smith adds a new feature into emailwiz. I'll open up another issue later.

I'll be using the same mail server, just uninstalling and reinstalling with the new domain name. I'll close this issue for now.
