### ISSUE TITLE
Archive and Trash folders Not Created, Can I use subdomains?

### ISSUE THREAD

**Issue by JPcode05** [LukeSmithxyz/emailwiz#188]
I used emailwiz to set up my mail server, but it created all the mailboxes except the Archive and Trash folders. Can I solve this by creating the mailboxes myself, or will that mess up anything with the Dovecot config files? What am I supposed to do?

Also, in #185, I was wondering if emailwiz supported (I found `$subdom` and `$maildomain` in the source code) or could add support for subdomains, such as having a server with the hostname and rDNS `mail.example.com` or something like `box.example.com` since I'm planning on having multiple servers under the same domain. (I know mail in a box recommends your server have a subdomain like `box.example.com` so I kind of want it to be like that.)

**Comment by emmatebibyte** [comment]
There appears to be no solution here, but I have the same issue, even after having created the dirs.
