### ISSUE TITLE
Cannot send mails

### ISSUE THREAD

**Issue by javiDev8** [LukeSmithxyz/emailwiz#189]
I set up my email server following the [Luke's video](https://www.youtube.com/watch?v=3dIVesHEAzc&t=71s) instructions and everything seems to work, no error messages or weird warning logs, and I can receive mails from platforms such gmail and hotmail but the mails I send don't arrive neither on inbox or spam. Then I receive an "Undelivered Mail Return to Sender" mail.
When the mail is sent to gmail the error details are:
`Status: 4.4.1
Diagnostic-Code: X-Postfix; connect to
    alt3.gmail-smtp-in.l.google.com[2607:f8b0:4023:401::1a]:25: Network is
    unreachable
`
and when is sent to hotmail:
`Status: 4.4.1
Diagnostic-Code: X-Postfix; connect to
    eur.olc.protection.outlook.com[104.47.22.161]:25: Connection timed out`
    
I'm using debian 10 on my vps.

**Comment by javiDev8** [comment]
I found that I got those errors cause vutlr is blocking the port 25, so is related with an already posted issue

**Comment by 187Qrly** [comment]
What? Doas vultr still block port 25? How did you fixed it?
