### ISSUE TITLE
Reverse DNS / PTR record

### ISSUE THREAD

**Issue by cl1pp0** [LukeSmithxyz/emailwiz#19]
Btw, it's also recommended to have a PTR record which points to your mail server:
https://wiki.hetzner.de/index.php/DNS-Reverse-DNS/en
Maybe you want to add this to your README.md.

**Comment by nicosalvadore** [comment]
Yes this is a good idea.

Usually, you have the ability to add the PTR record from the VPS provider portal, not your DNS registrar, as the PTR records are managed by the ones owning the IP space.

**Comment by LukeSmithxyz** [comment]
Can any of you give specifics: what it should look like in this case?

**Comment by nicosalvadore** [comment]
From what I understand about it (not an expert), the provider receving an inbound mail will make a reverse lookup on the email source IP address to retrieve the FQDN, using the PTR record.
Then a forward lookup is done using the FQDN from the previous step.
If they both match, the check is passed.

```
$ dig -x 207.148.31.239 -> lukesmith.xyz
$ dig lukesmith.xyz -> 207.148.31.239
```

**Comment by cl1pp0** [comment]
Yes, I can add the reverse DNS / PTR record in my VPS provider portal (unlike the domain settings / DNS entries). Check out this [doc by Vultr](https://www.vultr.com/docs/how-to-create-reverse-dns-or-ptr-records-in-the-vultr-control-panel) for example.

**Comment by dhruvsharma78** [comment]
@cl1pp0 @LukeSmithxyz  Created #29 to fix this issue
