### ISSUE TITLE
Hosting providers that don't block Port 25

### ISSUE THREAD

**Issue by JPcode05** [LukeSmithxyz/emailwiz#193]
Every time I buy a Linode server, I have to unlock Port 25. On one of my servers, I was rejected until I went on IRC. I don't wanna have to keep doing this, so are there any other hosting providers I can use?

**Comment by nikotile** [comment]
Not sure if this is your preference. Scaleway initially blocks SMTP, but after you do a KYC process you can unlock it on all of your VPS. You don't have to request to unblock it for each VPS.

**Comment by Theory-of-Everything** [comment]
As far as I am aware, most vps providers block mail ports to mitigate email spam. Most of these providers will unblock these ports after submitting a support ticket if you have enough history/use of the services.

It doesn't make all that much sense to create a bunch of servers if you plan to just have a single email setup (assuming that is what you want to accomplish with this script). Why exactly do you need to keep buying new instances from linode?

**Comment by SelfAdjointOperator** [comment]
I opened an account with Vultr a few months ago and added credit back then. This week I created a VPS with them for the first time. I messaged them on the support section of their website a couple of days after creating the VPS and they immediately unblocked port 25 as per their FAQ
Linking issue #172 for the record (today is 2022/01/16)
![Vultr](https://user-images.githubusercontent.com/66702639/149643958-ae7be42a-9100-4626-802b-8c361aba8292.png)
