### ISSUE TITLE
Can send emails but cannot receive any 

### ISSUE THREAD

**Issue by milkycereal** [LukeSmithxyz/emailwiz#196]
I can send emails perfectly fine but I am unable to receive any emails other than from myself (ie I email my email from my email)

**Comment by SelfAdjointOperator** [comment]
Have you read through `journalctl`? I had this issue and when I checked the logs `spamassassin` hadn't started / been enabled with `systemctl` and I had a couple of permission errors in `/etc/dovecot`. Mail had made it to my server but was kept somewhere in `/var` until I fixed the perms (and rebooted for good measure)

**Comment by milkycereal** [comment]
Afaik Dovecot and postfix are both working fine. I havent found any errors with journalctl but I mightve missed something with spamasassin. I do have a Mail folder in the user folder I created for my email

**Comment by milkycereal** [comment]
Turns out I forgot to actually unblock port 25 in the firewall All good now
