### ISSUE TITLE
opendkim.service: Can't open PID file /var/run/opendkim/opendkim.pid

### ISSUE THREAD

**Issue by VladimirVM** [LukeSmithxyz/emailwiz#20]
Hi. Run emailwiz.sh on 
> Ubuntu 18.04.3 LTS 
> CPU model               Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz
> CPU count               1
> Total memory            1008848 kB
> Total swap              0 kB
> Kernel name             Linux
> Kernel release          4.15.0-101-generic
> Kerne version           #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020
> Architecture            x86_64 x86_64

Problem with opendkim

```
● opendkim.service - OpenDKIM DomainKeys Identified Mail (DKIM) Milter
   Loaded: loaded (/lib/systemd/system/opendkim.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/opendkim.service.d
           └─override.conf
   Active: active (running) since Mon 2020-06-08 16:35:44 UTC; 1h 54min ago
     Docs: man:opendkim(8)
           man:opendkim.conf(5)
           man:opendkim-genkey(8)
           man:opendkim-genzone(8)
           man:opendkim-testadsp(8)
           man:opendkim-testkey
           http://www.opendkim.org/docs.html
  Process: 9799 ExecStart=/usr/sbin/opendkim -P /var/run/opendkim/opendkim.pid -p inet:8891@localhost (code=exited, status=0/SUCCESS)
 Main PID: 9810 (opendkim)
    Tasks: 6 (limit: 1151)
   CGroup: /system.slice/opendkim.service
           └─9810 /usr/sbin/opendkim -P /var/run/opendkim/opendkim.pid -p inet:8891@localhost

Jun 08 16:35:44 yousite systemd[1]: Stopped OpenDKIM DomainKeys Identified Mail (DKIM) Milter.
Jun 08 16:35:44 yousite systemd[1]: Starting OpenDKIM DomainKeys Identified Mail (DKIM) Milter...
Jun 08 16:35:44 yousite systemd[1]: opendkim.service: Can't open PID file /var/run/opendkim/opendkim.pid (yet?) after start: No such file or directory
Jun 08 16:35:44 yousite opendkim[9810]: OpenDKIM Filter v2.11.0 starting (args: -P /var/run/opendkim/opendkim.pid -p inet:8891@localhost)
Jun 08 16:35:44 yousite systemd[1]: Started OpenDKIM DomainKeys Identified Mail (DKIM) Milter.
```

How can i fix it?
Thanks!

**Comment by sir-marv** [comment]
Try specifying the PidFile in the /etc/opendkim.conf file:

PidFile                 /var/run/opendkim/opendkim.pid

**Comment by LukeSmithxyz** [comment]
Is this causing any issues? I have the error to and might fix it in the script above, but everything still seems to be working for me.

**Comment by LukeSmithxyz** [comment]
Well actually, looks like the issue is that the systemd service file overrides whatever you put to select that PIDFile.

**Comment by TheGejr** [comment]
I had this error. I fixed it by manually adding
`Socket                  inet:12301@localhost` to the `/etc/opendkim.conf`
And then restart the DKIM service


I had the error on a fresh Ubuntu 20.04, I know you are using 18.04.
Something seems (on Ubuntu 20.04) to bug out with the `sed` command on line 254.
See Issue #42

**Comment by VladimirVM** [comment]
Thanks, 

I can't check. I removed all and use another solution

**Comment by itjk** [comment]
@TheGejr's solution worked for me
