### ISSUE TITLE
Not receiving any emails

### ISSUE THREAD

**Issue by focus85** [LukeSmithxyz/emailwiz#209]
Everything was fine and all of the sudden now I can only send but not receive any email. I didn't change anything from the last working environment. Port 25 is opened.

**Comment by 2xx04** [comment]
Try using the default IMAP port 143. I had the same problem when using port 993.

**Comment by focus85** [comment]
> Try using the default IMAP port 143. I had the same problem when using port 993.

It doesn't even let me login with that port.

**Comment by 2xx04** [comment]
that's odd. my configuration is:

```
SMTP server: `mail.yourdomain.tld`
SMTP port: 587
Authentication Method: Normal password
Connection Security: STARTTLS

IMAP server: `mail.yourdomain.tld`
IMAP port: 143
Authentication Method: Normal password
Connection Security: STARTTLS
```

try checking the logs:
```
journalctl -xe | grep dovecot
journalctl -xe | grep postfix
```

**Comment by focus85** [comment]
based on 
```
journalctl -xe | grep dovecot
journalctl -xe | grep postfix
```
I found out I had some problem with lmtp plugins when I setup roundcube. I managed to fix the issue and I am able to send/receive emails EXCEPT, me.com (icloud) email keep rejecting my message... any idea as to why I can send almost every domain except icloud.com (me.com)

**Comment by 2xx04** [comment]
you can check on https://appmaildev.com/en/dkim for that, it'll list all the reasons why you might not able to send/recieve messages or blocked from certain email providers.

**Comment by LukeSmithxyz** [comment]
Man, I can't even send messages to iCloud. You probably just got an IP they marked as abusive years ago (I don't think they ever take them off).
