### ISSUE TITLE
How to manually mark spam/ham

### ISSUE THREAD

**Issue by microo8** [LukeSmithxyz/emailwiz#221]
So sometimes will spamassassin mark something as spam but it is not and I want to see the message from the sender. And likewise sometimes it will not catch a spam message.

How do I mark a message (ideally trough my email client) as spam/ham?
I searched the net for some tutorials and there is some sa-learn and a dovecot antispam plugin.
But this email setup stuff is complicated, that's why I used emailwiz in the first place.

**Comment by aselimov** [comment]
Not sure if you figured it out yet but what I have done is to use the local.cf file in /etc/spamassassin. To manually mark something as spam you just add a rule with "blacklist_from email@address.com" or "whitelist_from email@address.com".  I add this at the bottom of my local.cf file.
