### ISSUE TITLE
certfile valid even if certbot fails

### ISSUE THREAD

**Issue by mxraw** [LukeSmithxyz/emailwiz#223]
In line 48, the variable certfile will be set to a valid value even if certbot fails or doesn't exist. Ex:

```
$ dpkg -l certbot
dpkg-query: no packages found matching certbot
$ certdir="$(dirname "$(certbot certificates 2>/dev/null | grep "$maildomain\|*.$domain" -A 2 | awk '/Certificate Path/ {print $3}' | head -n1)")"
$ echo $certdir
.
$
```

This immediadetly becomes a problem in line 50 where the check does not fail, because... well, '.' is a valid directory. Instead of aborting, the script goes on creating broken configuration files for dovecot.

I think the execution of certbot should be extra so that not only the script aborts when it return value indicates failure but also certbot's error is outputted to stdin.

**Comment by LukeSmithxyz** [comment]
I see. The error his is because of the dirname that will return `.` if the command isn't present, which as you say, is a directory.
