### ISSUE TITLE
Sent mail not in sent dir

### ISSUE THREAD

**Issue by emmatebibyte** [LukeSmithxyz/emailwiz#225]
When mail is sent, it is not placed in the sent directory in ~/Mail.

**Comment by ran-deh** [comment]
You should find it in /home/YourUserName/Mail/Sent/cur

**Comment by emmatebibyte** [comment]
> You should find it in /home/YourUserName/Mail/Sent/cur
That's the issue, it is not there.

**Comment by emmatebibyte** [comment]
Sorry, the error was with k9 mail, it was not placing sent messages into the sent folder.
