### ISSUE TITLE
Not sending or allowing to log on

### ISSUE THREAD

**Issue by TheAcornHunter** [LukeSmithxyz/emailwiz#227]
Hi,

I have used this script before to set up a server, and it worked flawlessly, but today I tried to set it up with a new domain on a new machine, and it won't let me connect to the server outside my home network. I have forwarded ports 587 and 993. Even when I log in locally, mail does not send. I will update this as I try and fix it. 

Thanks

**Comment by TheAcornHunter** [comment]
Update: I have enabled port 25 as well, but I think the problem might be Postfix, which says active (exited) as it's status while all other services are running.

**Comment by LukeSmithxyz** [comment]
Postfix should say "active (exited)" if working properly. That is not the issue in itself.

So when you try to send mail, does it hang or is there an error on the command line?

What do you system logs say?

**Comment by RisuSofos** [comment]
I may also have a similar issue.
I can log into IMAP and get folders, but I cannot send or receive mail, and I have made sure ports 587 and 993 were both opened.
Granted, I am on Archlinux and had to modify the script slightly.

**Comment by LukeSmithxyz** [comment]
I mean in that case, it looks like the script is calling some directories that exist for Debian, but not Arch, so you'd have to mimic how Debian does things or change the settings the script sets.
