### ISSUE TITLE
CNAME records inconsistency

### ISSUE THREAD

**Issue by TheYellowArchitect** [LukeSmithxyz/emailwiz#235]
In README.md, it says
>**You need** two little DNS records set on your domain registrar's site/DNS server: (1) an MX record pointing to your own main domain/IP and (2) **a CNAME record for your mail. subdomain**.

"[Gmail's dumb - Just host your own mail server!](https://videos.lukesmith.xyz/w/kAqZB7FY568yDknhqCMeBn)" video-> creates 3 CNAME records.
"[Setting up a Website and Email Server in One Sitting (Internet Landchad)](https://videos.lukesmith.xyz/w/c1d4KKBe8iQ3sqL6W8vYDp)" video -> creates 0 CNAME records.
README.md -> Claims you should have 1 CNAME record

My question is, with emailwiz.sh, how many CNAME records should there be in the end?
I myself have managed to get a working email with 1 and even 2 CNAME records, and while my email works perfectly in sending and receiving (even encrypted emails), I get bizzare results from https://intodns.com/theyellowarchitect.com
![MX-Records](https://user-images.githubusercontent.com/25630803/187173880-a8d4849d-e84b-479b-aabd-fd777f8ababc.png)

Trying to delete 1 or 2 of the CNAME records, completely broke the connection to the email, and resulted in an even worse error
![NS-SOA-email-nameservers-epik](https://user-images.githubusercontent.com/25630803/187174128-73a46761-6cc7-4d9e-8a20-d3cda02ee5fe.png)

Yet, I can still send/receive emails without apparent problems.

So, my question is, how many CNAME records should there be, on a default email setup? Just give me a number or an image of epik's CNAME+MX records, I don't need an explanation or wall of text

**Comment by PR454D** [comment]
As per the script, and instructions in the video, I did add 3 TXT records,(btw my registrar is Namecheap. not that it matters.) I checked if my mail is being spam filtered (with mxtoolbox.com).. its not.. I also checked my domain with your suggested site. intodns.com. All's green... but mail is not sent through Thunderbird. All settings of thunderbird are correct. It even recognised and logged into the server. Only received mails are visible.

**Comment by PR454D** [comment]
> As per the script, and instructions in the video, ....

So, I checked my logs... and postfix is having some seizures.. the postfix service starts and exits for some reason. thats why it;s not sending mails

**Comment by PR454D** [comment]
Okay, the problem wasn't a config error, but a connection timed out error. Postfix sends the mail, but is not able to connect to the recipient's mail server.

**Comment by TheYellowArchitect** [comment]
I am confused on your messages, as they do not answer my question: How many CNAME records do you have to get a functional email?

If you are having issues sending an email, remember that when you change a CNAME record, it should take around 30 minutes to 1 day for DNS to properly "merge" the change, so for 30 minutes to 1 day after you change a CNAME record, your email does not work. I hope this helps in what I assume is a problem you have with your email.

**Comment by LukeSmithxyz** [comment]
You don't need any CNAME records to have email. It has nothing to do with mail whatsoever.

Set an MX record to `mail.` and then set A records (for IPv6 and IPv4) that direct to the IPs of your mail server. That is all you need. CNAMEs and ALIASes can do what A does and is easier if you hypothetically switch servers a lot (which you probably won't), but just using A is probably better, and perhaps I should change the readme to this effect.
