### ISSUE TITLE
PTR Records

### ISSUE THREAD

**Issue by SlidingHorn** [LukeSmithxyz/emailwiz#236]
I have my email set up on a Vultr VPS. In my settings, as instructed in the README, I have the Reverse DNS set to `mydomain.com` (obviously my actual domain). However, when I check on mxtoolbox, it tells me it is not a valid hostname.

I'm not sure where I went wrong here, but I cannot send email to gmail users from this account until I'm able to fix it, as they get rejected for not having a PTR record set up.

Would greatly appreciate any help I can get here.

**Comment by william-stacken** [comment]
Do you get "Reverse DNS is not a Valid Hostname" from mxlookup? So do I, I'm pretty sure it is because it tries to check if your IP address resolves to `mail.domain.com` instead of `domain.com`. That doesn't matter, it should work anyway.

Did you try `dig -x <your-ip>` just to see if you get your domain name? Also, are you sure that gmail rejects you because of your PTR record?

**Comment by SlidingHorn** [comment]
> Do you get "Reverse DNS is not a Valid Hostname" from mxlookup? 

Yes.

> Did you try `dig -x <your-ip>

gives back my domain (not `mail.`)

> are you sure that gmail rejects you because of your PTR record?

That's what the messages I get back from them say:

> The IP address sending this 550-5.7.25 message does not have a PTR record setup, or the corresponding 550-5.7.25 forward DNS entry does not point to the sending IP. As a policy, 550-5.7.25 Gmail does not accept messages from IPs with missing PTR records.

**Comment by william-stacken** [comment]
Just to make sure, your forward DNS points to just your IP address right? Could there be a NAT or firewall or something that updates the public IP address? What do you get if you run `curl ifconfig.me` on the server?

**Comment by SlidingHorn** [comment]
I don't understand any of what you just asked.

**Comment by SlidingHorn** [comment]
> What do you get if you run curl ifconfig.me on the server?

It returns the same IP address I have the domain pointed to....sorry for the delay on that response.

**Comment by fishnibble** [comment]
I'm having the same issue. Any resolve? I get the correct ip address as well. I tried reinstalling the script. I thought it might of been an issue with port 25 being block however, it was not blocked. My reverse DNS is pointed to my url. I'm pretty new to email so I hope I'm not missing something simple.

**Comment by SlidingHorn** [comment]
@fishnibble nothing so far =/

**Comment by 10leej** [comment]
It seems this might be an issue related to IPv6?  
https://serverfault.com/questions/1106769/gmail-does-not-accept-mail-from-a-new-vps-server-with-ptr-setup

**Comment by 10leej** [comment]
Same issue checking mail-tester.com it seems to be an issue relating to MX records

I get a total score of 6.8/10
https://www.mail-tester.com/test-9mkick825

**Comment by DashDashDashDashDash** [comment]
I got the same error. Fixed it by adding a AAAA record on my DNS settings, with my VPS' IPv6 address as the answer. This is apparently a really vague error message from Google though, as I've seen multiple different solutions on the internet.

**Comment by SlidingHorn** [comment]
> I got the same error. Fixed it by adding a AAAA record on my DNS settings, with my VPS' IPv6 address as the answer. This is apparently a really vague error message from Google though, as I've seen multiple different solutions on the internet.

I already have a AAAA record for my IPv6 address in my DNS settings, so that's not the cause.

**Comment by SlidingHorn** [comment]
Was there an update that fixed this issue @LukeSmithxyz?
