### ISSUE TITLE
Saner defaults

### ISSUE THREAD

**Issue by adastx** [LukeSmithxyz/emailwiz#241]
Would it be possible to change the default ports and sub-domain, so that standard mail clients can auto setup new mail accounts?

Having to tell my parents what to values to type in the IMAP and SMTP domain/port is not ideal :smile:

**Comment by LukeSmithxyz** [comment]
The defaults are literally as sane as it can possibly be. There is no variance in ports used. Modern IMAP is always 993 and SMTP is always 587 or 465, which should both be compatible here.

There certainly is no standard for subdomains, but `mail.` for both IMAP and SMTP is easiest for this use case so users don't use separate subdomains for a server of this scale and thus need multiple certificates, etc.

What you should do is complain to the developers of any client that is assuming "default" ports aside from the canonical locations, etc.

**Comment by adastx** [comment]
Thanks for clarifying.
