### ISSUE TITLE
Incorrect DKIM keytable entry

### ISSUE THREAD

**Issue by ljbkusters** [LukeSmithxyz/emailwiz#243]
I recently installed a mail server using emailwiz and found that I could not send mail. In thunderbird specifically, which I installed to quickly check if the server was running correctly, I got the error "service not available, try again later". A quick look at `journalctl` showed the following error message:
```
can't load key from /etc/postfix/dkim/mail.private: No such file or directory
```

indeed, `/etc/postfix/dkim/keytable` listed the following entry (I have replaced the actual domain name by `mydomain.xxx`):
```
mail._domainkey.mydomain.xxx mydomain.xxx:mail:/etc/postfix/dkim/mail.private
```

However the `mail.private` key is stored in `/etc/postfix/dkim/mydomain.xxx/mail.private` (note the extra subdirectory).
Changing the entry to the correct path, then reloading the opendkim and postfix using `systemctl` fixed the issue for me.

To me it seemed like this is not intended behaviour, so that's why I'm opening this issue. Since I'm new to mail servers I'm not sure at which point in the configuration this configuration mismatch occurs and if it's specific to emailwiz or not. I hope it helps anyone with a similar problems.

EDIT: okay I see you've closed this. I was working with an older version. I should have checked closed issues before opening this issue, sorry about that.

**Comment by LukeSmithxyz** [comment]
Yeah, this should've been fixed in e8f52cebf81d7f1e4202111efd95f74d4b4c088d. I'm guessing you installed before that fix.
