### ISSUE TITLE
Is there any brute force protection by default?

### ISSUE THREAD

**Issue by aquaspy** [LukeSmithxyz/emailwiz#249]
Hi,

I'm not sure if it is really necessary or needed, but I was just thinking:

Is there any brute protection enabled by default?

Thank you. I've been using my own email for almost 1 year now thanks to your script :)

**Comment by LukeSmithxyz** [comment]
No. This should be handled by other tools on your server.

I've thought about adding fail2ban by default, and that is something to look into, but the current brute force protection is: Having good passwords.
