### ISSUE TITLE
emailwiz with Cloudflare SSL

### ISSUE THREAD

**Issue by TheLostProgrammer** [LukeSmithxyz/emailwiz#250]
I am using Cloudflare with their SSL and I am getting the following output when running the script:
```
Note! You must first have a Let's Encrypt Certbot HTTPS/SSL Certificate for mail.example.com.

Use Let's Encrypt's Certbot to get that and then rerun this script.
```
I don't really know what to do with this situation, some help would be much appreciated.

**Comment by ran-deh** [comment]
@TheLostProgrammer Cloudflare proxy should be off for mail.example.com.

**Comment by ran-deh** [comment]
@TheLostProgrammer I am not familiar with Caddy. Take a look at lines 46 - 50 of the emailwiz script.
