### ISSUE TITLE
Add support for wildcard domains?

### ISSUE THREAD

**Issue by appeasementPolitik** [LukeSmithxyz/emailwiz#257]
In my opinion this should be added, as it takes extra effort to set up a wildcard domain (extra DNS records), which I think makes it likelier that someone would also want to use it for their mail server. 

If this gets the green light I can open a pull request.

**Comment by LukeSmithxyz** [comment]
What do you mean here? I mean the script doesn't set any DNS records and I assume that the A/AAAA records are already set on install.

**Comment by appeasementPolitik** [comment]
Currently the script checks for a `$maildomain` certificate and uses it if it exists, and if it does not exist it generates a new certificate for `$maildomain`. I am proposing that it also checks specifically for a `\*\.$domain` wildcard certificate, and uses it if it exists. Not to be confused with `*.$domain`, which does something else.

**Comment by LukeSmithxyz** [comment]
Ah, I see. Good call. I've added that.
