### ISSUE TITLE
is the $ after the -d there by an error?

### ISSUE THREAD

**Issue by adtyanair** [LukeSmithxyz/emailwiz#26]
https://github.com/LukeSmithxyz/emailwiz/blob/145a5e95d17a01019f9f0615f2b7ace7faa7e18f/emailwiz.sh#L228

the `/etc/postfix/dkim/mail.txt` ends with `DKIM key mail for $` when the $ is in the command.
when I remove the $, the file ends with `DKIM key mail for mydomain.tld`

**Comment by LukeSmithxyz** [comment]
Yeah I think you're right. I'll fix this, but it doesn't seem to have caused any huge problems...
