### ISSUE TITLE
mail users have ssh access

### ISSUE THREAD

**Issue by securityexper1488** [LukeSmithxyz/emailwiz#267]
By default with this config, mail users have access to ssh and can see all other user's and can go into the root directory.

**Comment by LukeSmithxyz** [comment]
You really shouldn't be allowing any ssh access via password authentication on your server in the first place. I'm not going to (nor cant I) set that up in this script, although it's probably suboptimal that I'm assuming everyone is already using best practices.

I suppose we could add `DenyGroups mail` to the sshd config as an extra safety measure, but that would also ruin it for people who *want* to have user accounts using ssh and mail.

I'll think about what's best.

**Comment by ASKaraferias** [comment]
In /etc/ssh/sshd_config you want to set AllowUsers to only allow the users you want to be able to ssh into the server to be able to do so, typically you only want one user to do that. Also be sure to disable password and pam authentication and enable PubkeyAuthentication. If this is set only users with the public key in their home dir will be able to log in either way. If you are using Vultr, be sure to check /etc/ssh/ssh_config.d/ for any additional config files, as sometimes they put a config file that enables Password based authentication in there, so even if you disable it from yout main sshd_config, it will remain enabled.

The script should not mess with the sshd config file, as that has the potential of locking someone outside of their server.
