### ISSUE TITLE
Thunderbird failed to find the settings for your email account

### ISSUE THREAD

**Issue by habem86** [LukeSmithxyz/emailwiz#27]
Hello, I followed every step of luke's video, but I run it on Ubuntu VPS, domain is from epik. When trying to login to thunderbird I get this: "Thunderbird failed to find the settings for your email account"
It eventually logged me in but it seems I can't receive or send emails, as it just won't connect to the email address. I got this error when running your script. It might be something easy to fix, but I am an absolute beginner. This what I got from the logs. Thanks for any help.

Job for opendkim.service failed because the control process exited with error code.
● opendkim.service - OpenDKIM DomainKeys Identified Mail (DKIM) Milter
     Loaded: loaded (/lib/systemd/system/opendkim.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2020-06-22 19:10:58 UTC; 46s ago
       Docs: man:opendkim(8)
             man:opendkim.conf(5)
             man:opendkim-genkey(8)
             man:opendkim-genzone(8)
             man:opendkim-testadsp(8)
             man:opendkim-testkey
             http://www.opendkim.org/docs.html
    Process: 46286 ExecStart=/usr/sbin/opendkim -x /etc/opendkim.conf (code=exited, status=78)

Jun 22 19:10:58 habe systemd[1]: opendkim.service: Control process exited, code=exited, status=78/CONFIG
Jun 22 19:10:58 habe systemd[1]: opendkim.service: Failed with result 'exit-code'.
Jun 22 19:10:58 habe systemd[1]: Failed to start OpenDKIM DomainKeys Identified Mail (DKIM) Milter.
Jun 22 19:10:58 habe systemd[1]: opendkim.service: Scheduled restart job, restart counter is at 5.
Jun 22 19:10:58 habe systemd[1]: Stopped OpenDKIM DomainKeys Identified Mail (DKIM) Milter.
Jun 22 19:10:58 habe systemd[1]: opendkim.service: Start request repeated too quickly.
Jun 22 19:10:58 habe systemd[1]: opendkim.service: Failed with result 'exit-code'.
Jun 22 19:10:58 habe systemd[1]: Failed to start OpenDKIM DomainKeys Identified Mail (DKIM) Milter.

-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The unit opendkim.service has entered the 'failed' state with result 'exit-code'.
Jun 22 19:13:58 habe systemd[1]: Failed to start OpenDKIM DomainKeys Identified Mail (DKIM) Milter.
-- Subject: A start job for unit opendkim.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- A start job for unit opendkim.service has finished with a failure.
-- 
-- The job identifier is 3960 and the job result is failed.
Jun 22 19:13:58 habe spamd[47271]: zoom: able to use 371/372 'body_0' compiled rules (99.731%)
Jun 22 19:13:58 habe systemd-resolved[584]: Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP.
Jun 22 19:13:58 habe spamd[47271]: spamd: server started on IO::Socket::IP [::1]:783, IO::Socket::IP [127.0.0.1]:783 (running version 3.4.4)
Jun 22 19:13:58 habe spamd[47271]: spamd: server pid: 47271
Jun 22 19:13:58 habe spamd[47271]: spamd: server successfully spawned child process, pid 47275
Jun 22 19:13:58 habe systemd[1]: Started Perl-based spam filter using text analysis.
-- Subject: A start job for unit spamassassin.service has finished successfully
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- A start job for unit spamassassin.service has finished successfully.
-- 
-- The job identifier is 3620.
Jun 22 19:13:58 habe spamd[47271]: spamd: server successfully spawned child process, pid 47280
Jun 22 19:13:58 habe useradd[47281]: failed adding user 'dmarc', data deleted
Jun 22 19:13:58 habe spamd[47271]: prefork: child states: II

**Comment by habem86** [comment]
Okay it now seems to work, I can receive emails but can't send them, it always times out. I have port 25 unblocked by vultr and allowed in firewall.

**Comment by s0m3OnE47** [comment]
https://github.com/LukeSmithxyz/emailwiz/issues/18
Try this
