### ISSUE TITLE
Error locating or installing SSL certificate

### ISSUE THREAD

**Issue by SolacianAllie** [LukeSmithxyz/emailwiz#278]
ive spent days looking into this myself and officially have no idea whats happening.
ive been following this tutorial
https://www.makeuseof.com/make-your-own-raspberry-pi-email-server/
but had to use the certbot website to guide installing certbot as the link on the tutorial doesnt work, but every time i get to the mail server part, i get the SSL error, ive tried using separate SSL certificate creators, but every time i get this error and cannot continue

**Comment by LukeSmithxyz** [comment]
That guide is using Apache. You might want to get a certificate manually yourself since there can be some interference with it.

I've made the script try to adjust to Apache servers, but I've never had the time to check since I only really use Nginx if anything.
