### ISSUE TITLE
DKIM Test fails with error: fail (bad signature) 

### ISSUE THREAD

**Issue by cfRIKO** [LukeSmithxyz/emailwiz#28]
After running the script and adding the TXT records to my Domains DNS records, I did the DKIM Test at https://www.appmaildev.com/en/dkim but it fails telling me that my signature is invalid.

**Comment by s0m3OnE47** [comment]
https://github.com/LukeSmithxyz/emailwiz/issues/18 
This solved for me

**Comment by cfRIKO** [comment]
Seems like the output in "dns_emailwizard" is missing the output for the hash used.
Output of /etc/postfix/dkim/mail.txt:
![image](https://user-images.githubusercontent.com/40830087/85700951-2dc2f300-b6dd-11ea-8d4b-ecdfdac92acf.png)
Output of dns_emailwizard
![image](https://user-images.githubusercontent.com/40830087/85701019-3ddad280-b6dd-11ea-8bb5-69056b082cbb.png)

Updating the TXT record with the h-option solved the problem for me
