### ISSUE TITLE
DNS records not recorded?

### ISSUE THREAD

**Issue by carterw** [LukeSmithxyz/emailwiz#281]
"The script will create a file, ~/dns_emailwiz that will list our the records for your convenience"

I ran the script and followed all the instructions, and it works. I can send and receive email through the resulting server. But I do not see a ~/dns_emailwiz file and I don't see a place in the script that creates one.

**Comment by william-stacken** [comment]
The README seems to be outdated, it's actually called `~/dns_emailwizard` as can be seen [here](https://github.com/LukeSmithxyz/emailwiz/blob/bcfa1b45ad9a568dda98de37262f867dd5528869/emailwiz.sh#L354). Did you check if that file exists?

**Comment by MoritzMoreira** [comment]
I cannot find the file either, neither `dns_emailwiz` nor `dns_emailwizard`. I looked in `home/username`, and tried `find -name "dns_emailwizard"`.
