### ISSUE TITLE
Use "spamd" instead of "spamassassin" for systemd and configuration files on Debian 12 bookworm

### ISSUE THREAD

**Issue by andrewrunxiyu** [LukeSmithxyz/emailwiz#282]
While bootstrapping my email setup on my new Debian 12 bookworm VPS, I encountered the following error in emailwiz's output:
```
sed: can't read /etc/default/spamassassin: No such file or directory                                                                                  
Restarting spamassassin...
Failed to restart spamassassin.service: Unit spamassassin.service not found.                                                
Failed to enable unit: Unit file spamassassin.service does not exist.
```
Apparently, Debian 12 bookworm uses /etc/default/spamd in place of /etc/default/spamassassin, see [Debian bug #1020859](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1020859) for context. Modifying /etc/default/spamd according to the process of the script, and running `systemctl enable --now spamd` seems to solve it for me.

**Comment by janilowski** [comment]
Had the same issue while setting up a server yesterday.
I think the best way to solve this would be to check if `/etc/default/spamassassin` exists and if not, then write to `/etc/default/spamd`? This new if statement could be removed when Debian 11 support is dropped.
Should be quite simple, I might do a pull request soon.

**Comment by andrewrunxiyu** [comment]
This commits checks for /etc/default/spamassassin. If it exists, it's
passed through sed to modify the CRON variable as usual, and
spamassassin.service is enabled and restarted.

If /etc/default/spamassassin does not exist, but /etc/default/spamd
exists, we modify /etc/default/spamd instead, and restart and enable
spamd.service.

This has to be done because Debian 12 introduced this breaking change:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1020859

Apologies for my previous commit which introduced a new "README" file
specifically for my fork of the repository. I've modified my patch to
remove it, please accept this version of the patch instead.

Signed-off-by: Andrew Yu ***@***.***>
---
 emailwiz.sh | 20 +++++++++++++++++---
 1 files changed, 17 insertions(+), 3 deletions(-)

diff --git a/emailwiz.sh b/emailwiz.sh
index 2e24c57..1c56f52 100644
--- a/emailwiz.sh
+++ b/emailwiz.sh
@@ -318,9 +318,23 @@ enabled = true
 enabled = true" > /etc/fail2ban/jail.d/emailwiz.local
 
 # Enable SpamAssassin update cronjob.
-sed -i "s|^CRON=0|CRON=1|" /etc/default/spamassassin
-
-for x in spamassassin opendkim dovecot postfix fail2ban; do
+if [ -f /etc/default/spamassassin ]
+then
+	sed -i "s|^CRON=0|CRON=1|" /etc/default/spamassassin
+	printf "Restarting spamassassin..."
+	service spamassassin restart && printf " ...done\\n"
+	systemctl enable spamassassin
+elif [ -f /etc/default/spamd ]
+then
+	sed -i "s|^CRON=0|CRON=1|" /etc/default/spamd
+	printf "Restarting spamd..."
+	service spamd restart && printf " ...done\\n"
+	systemctl enable spamd
+else
+	printf "!!! Neither /etc/default/spamassassin or /etc/default/spamd exists, this is unexpected and needs to be investigated"
+fi
+
+for x in opendkim dovecot postfix fail2ban; do
 	printf "Restarting %s..." "$x"
 	service "$x" restart && printf " ...done\\n"
 	systemctl enable "$x"
-- 
2.39.2

**Comment by andrewrunxiyu** [comment]
Alright, looks like using git-send-email with GitHub doesn't work properly. I've submitted a patch with git-send-email privately to Luke, and I currently "maintain" [a fork with the change (but with an extra README file clarifying the situation](https://git.andrewyu.org/andrew/forks/emailwiz.git/commit/?id=a42189b89ecaaf45e05f8b41907dd4f755fcd3e0).
