### ISSUE TITLE
Sieve script error storing on the root user folder 

### ISSUE THREAD

**Issue by Yoquec** [LukeSmithxyz/emailwiz#285]
# Problem

I noticed yesterday that I had my `journalctl` & `mail.err` filled with the same error over and over, where sieve is trying to do something inside the root user folder:

```
Jul 02 11:40:39 localhost postfix/local[373457]: 9DE3D43405: to=<root@example.com>, orig_to=<root>, relay=local, delay=122198, delays=122196/2.5/0/0.07, dsn=4.3.0, status=deferred (temporary failure. Command output: lda(root): Error: net_connect_unix(/run/dovecot/stats-writer) failed: Permission denied )
Jul 02 11:40:39 localhost dovecot[373568]: lda(root)<373568><GWaXNzdioWRAswUAboEwrg>: Error: chdir(/root/) failed: Permission denied (euid=65534(nobody) egid=65534(nogroup) missing +x perm: /root, dir owned by 0:0 mode=0700)
Jul 02 11:40:39 localhost dovecot[373568]: lda(root)<373568><GWaXNzdioWRAswUAboEwrg>: Error: sieve: file storage: Failed to stat sieve storage path: stat(/root/.sieve) failed: Permission denied (euid=65534(nobody) egid=65534(nogroup) missing +x perm: /root, dir owned by 0:0 mode=0700)
Jul 02 11:40:39 localhost dovecot[373568]: lda(root)<373568><GWaXNzdioWRAswUAboEwrg>: Error: stat(/root/Mail/Inbox/tmp) failed: Permission denied (euid=65534(nobody) egid=65534(nogroup) missing +x perm: /root, dir owned by 0:0 mode=0700)
Jul 02 11:40:39 localhost dovecot[373568]: lda(root)<373568><GWaXNzdioWRAswUAboEwrg>: Error: sieve: msgid=<20230701143502.9B09143714@mail.example.com>: failed to store into mailbox 'INBOX': Internal error occurred. Refer to server log for more information. [2023-07-02 11:40:39]
Jul 02 11:40:39 localhost dovecot[373568]: lda(root)<373568><GWaXNzdioWRAswUAboEwrg>: Error: sieve: Execution of script /var/lib/dovecot/sieve/default.sieve was aborted due to temporary failure
```

Each of these error traces begin with postfix trying to do something to the root user, maybe trying to send mail to it (`to=<root@example.com>`)?

It then complains about trying to store something into `mailbox 'INBOX'`, but the root user is not in the mail group nor does it have a `Mail` folder.

Why is this happening?

# What I have tried
I saw in the script that Postfix uses Dovecot for authenticating using PAM, and tried to restrict access to the root user as indicated in [the dovecot wiki](https://wiki2.dovecot.org/Authentication/RestrictAccess), but the problem persists.

Does somebody know what is happening? And how to go about fixing it?

**Comment by theobori** [comment]
You should try to change the `stats-writer` unix socket permissions.

I had the same problem and it worked for me, I added the following lines to `/etc/dovecot/dovecot.conf`.

```conf
service stats {
  unix_listener stats-writer {
    mode = 0666
  }
}
```

**Comment by Yoquec** [comment]
Thank you very much for the answer!

I had the mode currently on 0660. Changed it. I'll post (and reopen) here if anything still is going wrong!
