### ISSUE TITLE
Excluded cipher causing interoperability issues with outlook.

### ISSUE THREAD

**Issue by zeyadtamimi** [LukeSmithxyz/emailwiz#292]
While looking at my server logs I noticed that the mail coming in from outlook resulted in:
`warning: TLS library problem: error:0A0000C1:SSL routines::no shared cipher:ssl/statem/statem_srvr.c:2220:`

Further examining the logs seemed to indicate that the connection fell back to an unencrypted mode as I don't see any reference to an SSL connection being established or cipher being negotiated.

After disabling the cipher blacklist `smtpd_tls_exclude_ciphers` I sent another test email and through the logs I can see that the connection was using TLSv1.2 and the negotiated cipher suite was `ECDHE-ECDSA-AES256-GCM-SHA384`

Reading more into this, I could not find anything sub optimal about this particular cipher suite. Is the blanket exclusion of everything using ECDSA warranted here?

**Comment by LukeSmithxyz** [comment]
I've temporarily disabled the cipher list until I can check some more things.

I noticed that mails from other major sites were not going through if they had obsolete ciphers. (Even major banks and institutions.)

I think it's best to let the servers receive the mail obviously, so until I discern which should *actually* be excluded, I will not use the cipher blocklist.

**Comment by hasanparasteh** [comment]
@LukeSmithxyz can you provide a patch?
