### ISSUE TITLE
Emails get sent to spam

### ISSUE THREAD

**Issue by TheMadRuffian** [LukeSmithxyz/emailwiz#30]
On providers like Gmail and Outlook, the email gets sent to spam folder even though they passed the DKIM test. On Posteo, it gets blocked outright by "zen.spamhaus.org" and sent back to me. Now seemingly, Posteo had reported the mail server and now it says "RBL listed" while testing for DKIM. Any solutions?

**Comment by im-down** [comment]
if you know the person you are (supposedly) going to send emails to tell him to add the email as a contact. other than that i wouldn't know how to fix

**Comment by cfRIKO** [comment]
Some email providers require ptr records for your mail server to work

**Comment by LukeSmithxyz** [comment]
Yes, add a PTR record and check what the README says about public spam filters.
