### ISSUE TITLE
mail server configuration doesn't work with e-mail clients on iPhone

### ISSUE THREAD

**Issue by leybodv** [LukeSmithxyz/emailwiz#300]
Hi,

I installed mail server on ubuntu server following [this video](https://www.youtube.com/watch?v=3dIVesHEAzc), and everything works like a charm. I setup email clients on linux (thunderbird) and android (edison mail). However I failed to setup any client on iphone, although I use the same settings as for other clients. The only difference between android and iphone configuration is that on android I have option SSL/TLS for IMAP security, while on iphone there is only TLS. I am not sure if this is relevant.

Could you please help to change server configuration so that it works with iOS email clients? Or give a hint how can I find the problem by myself.

Relevant logging information:

> Nov 24 17:02:24 mydomain dovecot: imap-login: Login: user=<myuser>, method=PLAIN, rip=myip, lip=serverip, mpid=505699, TLS, session=<gb2K6ugKxU1t/b6N>
> Nov 24 17:02:24 mydomain postfix/submission/smtpd[505700]: connect from unknown[myip]
> Nov 24 17:02:24 mydomain postfix/submission/smtpd[505700]: SSL_accept error from unknown[myip]: -1
> Nov 24 17:02:24 mydomain postfix/submission/smtpd[505700]: warning: TLS library problem: error:0A0000C1:SSL routines::no shared cipher:../ssl/statem/statem_srvr.c:2220:
> Nov 24 17:02:24 mydomain postfix/submission/smtpd[505700]: lost connection after STARTTLS from unknown[myip]
> Nov 24 17:02:24 mydomain postfix/submission/smtpd[505700]: disconnect from unknown[myip] ehlo=1 starttls=0/1 commands=1/2

**Comment by hasanparasteh** [comment]
same problem here. it appeared magically after 6 month of using postfix...

**Comment by nonholamilza** [comment]
My personal settings for iOS are set in `Settings > Mail (App) > Account`, there you can add new account with other options.

Incoming settings:

> Host: mail.domain.com
> User: alians@domain.com

Outcoming settings:

> Host: mail.domain.com
> Username: alians
> Use SSL: ON
> Autentication: Password
> Port: 587

Advanced > Settings for incoming mail

> Use SSL: ON
> Autentication: Password
> Port: 993

**Comment by leybodv** [comment]
> My personal settings for iOS are set in `Settings > Mail (App) > Account`, there you can add new account with other options.
> 
> Incoming settings:
> 
> > Host: mail.domain.com
> > User: [alians@domain.com](mailto:alians@domain.com)
> 
> Outcoming settings:
> 
> > Host: mail.domain.com
> > Username: alians
> > Use SSL: ON
> > Autentication: Password
> > Port: 587
> 
> Advanced > Settings for incoming mail
> 
> > Use SSL: ON
> > Autentication: Password
> > Port: 993

Hey, it worked! Thanks! Although beside native iOS client, others still don't work. So wierd, but definetly not related to Luke's configuration. Thanks a lot again!
