### ISSUE TITLE
Error: Connection to SMTP Server failed

### ISSUE THREAD

**Issue by marlonivo** [LukeSmithxyz/emailwiz#309]
**Error:** 

```
Failed to send the message.
The message could not be sent because the connection to the SMTP server mail.marlonivo.xyz failed. The server is either unavailable or rejecting SMTP connections. Please check the SMTP server settings and try again.
```

**I did anything jus like in the Video Explanation of luke, its still showing up. How can i fix this?**

![mailhealth](https://github.com/LukeSmithxyz/emailwiz/assets/110742116/56d4d401-7939-4f8d-83f6-45374ecec863)

**Comment by rogsme** [comment]
I had this issue after an update on my mail server. It looks like emailwiz is not compatible with `postfix > 3.5.18-0+deb11u1` 

Try downgrading to version 3.5.18-0+deb11u1 using this:

```
sudo apt install postfix=3.5.18-0+deb11u1 postfix-pcre=3.5.18-0+deb11u1
```

**Comment by marlonivo** [comment]
```
E: Version '3.5.18-0+deb11u1' for 'postfix' was not found
E: Version '3.5.18-0+deb11u1' for 'postfix-pcre' was not found
```

**Comment by rogsme** [comment]
Did you ran a `sudo apt update` before? What version of Debian are you using?

**Comment by marlonivo** [comment]
I did, im using Debian: 
`6.1.0-15-arm64 #1 SMP Debian 6.1.66-1 aarch64`

**Comment by rogsme** [comment]
> I did, im using Debian: `6.1.0-15-arm64 #1 SMP Debian 6.1.66-1 aarch64`

Oh, you are using ARM, you should have started with that... Sorry, but I can help you there! Use `apt` to look for a lower version for `postfix` and `postfix-pcre` and install it.

**Comment by marlonivo** [comment]
```
E: Version '3.5.18-0+deb11u1' for 'postfix' was not found                                             
E: Version '3.5.18-0+deb11u1' for 'postfix-pcre' was not found 
```

I cant find the right Version, I either need to add another source to the sources.list or install and compile it manually, which I'd like to avoid. Do you have an other idea?

**Comment by rogsme** [comment]
> ```
> E: Version '3.5.18-0+deb11u1' for 'postfix' was not found                                             
> E: Version '3.5.18-0+deb11u1' for 'postfix-pcre' was not found 
> ```
> 
> I cant find the right Version, I either need to add another source to the sources.list or install and compile it manually, which I'd like to avoid. Do you have an other idea?

I already told you:

> Use apt to look for a lower version for postfix and postfix-pcre and install it.

**Comment by marlonivo** [comment]
Hey,
i have tried it several times and failed, do you have a referral link to a guide or can you give me one yourself?

**Comment by rogsme** [comment]
A quick internet search yielded the following solutions:

```
apt-cache madison postfix # Gets the available postfix packages 
apt-cache madison postfix-pcre # Gets the available postfix-pcre packages
```

If you need to know more about how `apt-cache` works, read the manpage `man apt-cache`.

You can also run `lsb_release -a`, get your Debian version and search manually on the Debian packages website: https://packages.debian.org/bookworm/postfix

**Comment by jptrzy** [comment]
I had the same issue.

**Comment by marlonivo** [comment]
> I had the same issue.

It was actually not the Postfix Version, what led to the error was the Port that was Blocked (im at Hetzner). After i requested to open them, it worked literally immediatly. Even the test mails i sent from 3 Weeks ago, came in. Luke mentiones this not in the Video but on the README.md. Maybe he mentioned it on his Video but i couldn't remember.

```
Unblock your ports
While the script enables your mail ports on your server, it is common practice for all VPS providers to block mail ports on their end by default. Open a help ticket with your VPS provider asking them to open your mail ports and they will do it in short order.
```

Solution: 
Ask to open port 465 and 993 for your mail-server.
