### ISSUE TITLE
Please point your domain (domain.com) to your server's ipv6 address.

### ISSUE THREAD

**Issue by sokkoban** [LukeSmithxyz/emailwiz#312]
Hello,
I'm trying to install on ubuntu 22.04 server but get this error: 
Please point your domain (domain.com) to your server's ipv6 address.

**Comment by capsload3** [comment]
Same for me

**Comment by DarKOrange75** [comment]
Same for me :-(

**Comment by DarKOrange75** [comment]
Thank you.

**Comment by LukeSmithxyz** [comment]
The actual solution is to follow the directions and "Point your domain to your server's IPv6 address."

**Comment by paulfrische** [comment]
> The actual solution is to follow the directions and "Point your domain to your server's IPv6 address."

I have the same issue (on linode) and I have set the same records for IPv4 and IPv6. Whois seems to recognize them but the "host" command doesn't (`;; communications error to ::1#53: connection refused`). haven't set any firewall whatsoever
