### ISSUE TITLE
Instructions for adding DNS records could be more clear

### ISSUE THREAD

**Issue by chadlinux** [LukeSmithxyz/emailwiz#318]
My MX and CNAME records look incorrect. What do I need to fix? Thanks, all!

1. I am using the old step-by-step tutorial for setting up an Vultr-hosted VPS email server on landchad.net, rather than using the emailwiz script since both methods use mostly the same set of commands.
2. I am confused by how to properly establish CNAME and MX records on my Epik domains account based on the instructions Luke gave on ["Setting up an email inbox"](https://landchad.net/mail/inbox/). Trying to follow Luke's steps literally, but unsure what mistakes I am making. 

He writes:

```
We also need two little DNS records set on your domain registrar’s site/DNS server:

    An MX record. Just put your domain, example.org, in the “Points to” field.
    A CNAME record. Host field: mail.example.org. “Points to” field: example.org.
```

Epik domains gave me a warning when I tried typing my website's domain name "benpearce.xyz", saying:

`Warning: Your MX record will be treated as
"benpearce.xyz.benpearce.xyz".
Press OK to add trailing dot and have your MX record treated as
"benpearce.xyz"
Press Cancel to leave your input unchanged`

My MX record currently looks like this:
![benpearce_xyz MX record](https://github.com/LukeSmithxyz/emailwiz/assets/168049833/40d9e8ef-d98b-4426-8cfb-a25a33955c29)

My CNAME record currently looks like this:
![benpearce_xyz CNAME record](https://github.com/LukeSmithxyz/emailwiz/assets/168049833/c936990c-02e6-458e-bde6-82a8b1621f8a)

[Intodns](intodns.com) has some warnings about my MX and CNAME records of my website (benpearce.xyz).
![IndoDNS warnings](https://github.com/LukeSmithxyz/emailwiz/assets/168049833/10b76f05-f579-4096-8924-39a626bfd9d0)

**Comment by chadlinux** [comment]
Hi again,

Ok, I think I fixed the issue. You need to follow EXACTLY what landchad.net tells you to do for the MX and CNAME DNS records if you're using Epik domains. Be careful, because Epik domains will try sticking a trailing period on your domain name.

For the MX record, he says:

`Just put your domain, example.org, in the “Points to” field.`

When I tried doing this, Epik domains spit up a warning menu. There are two options you can chose from, "OK" or "Cancel".

1. Click "OK" to adding a trailing period to my domain name and proceed. **_DON'T DO THIS_**! It will screw up your MX record. IntoDNS will complain like I showed in my screenshot.
2. Click "Cancel" to leave "points to" field as-is **_WITHOUT_** the trailing period and proceed with input unchanged. **_DO THIS_**!
![benpearce_xyz MX record warning](https://github.com/LukeSmithxyz/emailwiz/assets/168049833/4bc4eb27-8a49-46ac-a4bc-038bf5a3f0c6)

Now my IntoDNS result for my website passes all the checks! :+1: 

![IntoDNS MX and CNAME DNS records good](https://github.com/LukeSmithxyz/emailwiz/assets/168049833/5c0fe5b0-24a2-4494-b0ff-a057776d3489)

**Comment by D0LLYNH0** [comment]
@chadlinux, this has nothing to do with your problem, but since I can inform you, why not? Upon inspecting your domain, I noticed that your CAA record is incorrect. The value “1” in the flag has no meaning; I believe you meant 128 (critical bit), which is often confused with 1. See [here](https://letsencrypt.org/docs/caa/#what-to-put-in-the-record) and [here](https://www.gogetssl.com/wiki/problems/caa-record/#:~:text=f-,%3Cflag%3E,-The%20flag%20value).

**Comment by chadlinux** [comment]
> @chadlinux, this has nothing to do with your problem, but since I can inform you, why not? Upon inspecting your domain, I noticed that your CAA record is incorrect. The value “1” in the flag has no meaning; I believe you meant 128 (critical bit), which is often confushttps://github.com/LukeSmithxyz/emailwiz/issues/318#issuecomment-2167225086ed with 1. See [here](https://letsencrypt.org/docs/caa/#what-to-put-in-the-record) and [here](https://www.gogetssl.com/wiki/problems/caa-record/#:~:text=f-,%3Cflag%3E,-The%20flag%20value).
I have reinstalled Debian a few times since I wrote this. Whatever you currently see for my website was done using the emailwiz script.

This forum thread that I opened originally was using the landchad.net tutorials for making your own website. I did manage to send an email from my server using terminal that way, but had no idea how to connect to it using an email client such as thunderbird.

I had even less success with his emailwiz script as I mentioned [here](https://github.com/LukeSmithxyz/emailwiz/issues/319)
