### ISSUE TITLE
DKIM none DomainKey none while testing on https://appmaildev.com/en/dkim

### ISSUE THREAD

**Issue by romanfazulianov** [LukeSmithxyz/emailwiz#32]
Hi, Luke! I used couple of your last videos and successfully installed nginx and mail server. I found that despite the fact i added txt dns records as needed,  https://appmaildev.com/en/dkim test says none for both DKIM and DomainKey. Test passed, but "none" looks weird for me. Is this correct behavior? mail._domainkey txt record is on its place in dns records

**Comment by romanfazulianov** [comment]
Additional info:
Found this in install script logging

```
Restarting opendkim...Job for opendkim.service failed because the control process exited with error code.
See "systemctl status opendkim.service" and "journalctl -xe" for details.
```
Then i ran status and found this. 
![Screenshot from 2020-06-23 14-36-28](https://user-images.githubusercontent.com/5006121/85399146-01816800-b55f-11ea-85bc-b90e810745be.png)

**Comment by projectunderscore** [comment]
I had this issue too. The top answer here seemed to straighten things out.

https://serverfault.com/questions/847435/cant-change-opendkim-socket-in-debian-stretch-in-etc-default-opendkim

`/lib/opendkim/opendkim.service.generate`
`systemctl daemon-reload`
`service opendkim restart`

**Comment by romanfazulianov** [comment]
@projectunderscore many thanks to you! It works correctly now and test successfully passes for DKIM.
