### ISSUE TITLE
Lack of IPV6 Support

### ISSUE THREAD

**Issue by Tair-Karanfili** [LukeSmithxyz/emailwiz#325]
I am using a VPS provider that exclusively operates only IPV4 addresses for their servers and not IPV6. As a prerequisite of running the script you need an  an AAAA name record pointing to your IPV6 address. Can I get around this somehow?

**Comment by msbrewer** [comment]
What service are you using that doesn't have ipv6 service?  If they do not have an option for ipv6 there isn't a way to fake it.  but you may be able to edit the scripts for ipv6 to not require it, but can't be sure it would work as it may be reliant on ipv6 elsewhere.
