### ISSUE TITLE
luke plz help me

### ISSUE THREAD

**Issue by youssef-cmyk** [LukeSmithxyz/emailwiz#33]
i just install your "emailwiz" but i get an error wen i wont send emails

ps : i run the script in debian vps hosted in aws
plz help me

i have check logs  in /var/log/mail.err and it giv me this

`Jun 23 12:04:18 ip-172-31-43-81 spamd[16960]: Can't locate Mail/SpamAssassin/CompiledRegexps/body_0.pm in @INC (you may need to install the Mail::SpamAssassin::CompiledRegexps::body_0 module) (@INC contains: /var/lib/spamassassin/compiled/5.028/3.004002 /var/lib/spamassassin/compiled/5.028/3.004002/auto /usr/share/perl5 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at (eval 1219) line 1.`

**Comment by garritfra** [comment]
Try installing the module that it's telling you is missing:

```
perl -MCPAN -e 'install Mail::SpamAssassin::CompiledRegexps::body_0'
```

**Comment by youssef-cmyk** [comment]
hello. i have Redeploy the debian server and every things works but it don't wont to sent emails to gmail.

i have check the mail.log fille in `/var/log/mail.log` i get a Connection timed out canyou help me @garritfra 

```
Jun 24 14:05:38 ip-172-31-46-69 postfix/smtp[20766]: connect to gmail-smtp-in.l.google.com[142.250.10.26]:25: Connection timed out
Jun 24 14:05:38 ip-172-31-46-69 postfix/smtp[20766]: connect to gmail-smtp-in.l.google.com[2607:f8b0:4023::1b]:25: Network is unreachable

```

**Comment by garritfra** [comment]
Try pinging some other website and see if you have a connection at all

`ping github.com`

**Comment by youssef-cmyk** [comment]
of course i have intenet connection

```
root@ip-172-31-46-69:~# ping github.com
PING github.com (140.82.114.4) 56(84) bytes of data.
64 bytes from lb-140-82-114-4-iad.github.com (140.82.114.4): icmp_seq=1 ttl=40 time=11.0 ms
64 bytes from lb-140-82-114-4-iad.github.com (140.82.114.4): icmp_seq=2 ttl=40 time=11.1 ms
64 bytes from lb-140-82-114-4-iad.github.com (140.82.114.4): icmp_seq=3 ttl=40 time=11.1 ms
64 bytes from lb-140-82-114-4-iad.github.com (140.82.114.4): icmp_seq=4 ttl=40 time=11.1 ms
64 bytes from lb-140-82-114-4-iad.github.com (140.82.114.4): icmp_seq=5 ttl=40 time=11.1 ms
64 bytes from lb-140-82-114-4-iad.github.com (140.82.114.4): icmp_seq=6 ttl=40 time=11.2 ms
X64 bytes from lb-140-82-114-4-iad.github.com (140.82.114.4): icmp_seq=7 ttl=40 time=11.1 ms
64 bytes from lb-140-82-114-4-iad.github.com (140.82.114.4): icmp_seq=8 ttl=40 time=11.1 ms
64 bytes from lb-140-82-114-4-iad.github.com (140.82.114.4): icmp_seq=9 ttl=40 time=11.2 ms
64 bytes from lb-140-82-114-4-iad.github.com (140.82.114.4): icmp_seq=10 ttl=40 time=11.2 ms
64 bytes from lb-140-82-114-4-iad.github.com (140.82.114.4): icmp_seq=11 ttl=40 time=11.2 ms
64 bytes from lb-140-82-114-4-iad.github.com (140.82.114.4): icmp_seq=12 ttl=40 time=11.1 ms
64 bytes from lb-140-82-114-4-iad.github.com (140.82.114.4): icmp_seq=13 ttl=40 time=11.1 ms
^C
--- github.com ping statistics ---
13 packets transmitted, 13 received, 0% packet loss, time 30ms
rtt min/avg/max/mdev = 11.030/11.118/11.237/0.091 ms
root@ip-172-31-46-69:~# 
```

**Comment by cfRIKO** [comment]
Try to ping the gmail mail server

**Comment by youssef-cmyk** [comment]
@cfRIKO 


```
admin@ip-172-31-46-69:~$ ping gmail-smtp-in.l.google.com
PING gmail-smtp-in.l.google.com (172.253.112.27) 56(84) bytes of data.
64 bytes from 172.253.112.27: icmp_seq=1 ttl=90 time=31.2 ms
64 bytes from 172.253.112.27: icmp_seq=2 ttl=90 time=31.2 ms
64 bytes from 172.253.112.27: icmp_seq=3 ttl=90 time=31.3 ms
64 bytes from 172.253.112.27: icmp_seq=4 ttl=90 time=31.3 ms
64 bytes from 172.253.112.27: icmp_seq=5 ttl=90 time=31.3 ms
^C
--- gmail-smtp-in.l.google.com ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 200ms
rtt min/avg/max/mdev = 31.176/31.255/31.311/0.122 ms
admin@ip-172-31-46-69:~$ 

```

but it still not working 
maybe because i'm using aws
but i have open all tcp ports

**Comment by LukeSmithxyz** [comment]
Contact your VPS provider and request they open port 25.

**Comment by ShivamJoker** [comment]
I am using AWS and I have port 25 open bu I am still getting gmail server unreachable

**Comment by fuwn** [comment]
> I am using AWS and I have port 25 open bu I am still getting gmail server unreachable

Same here, but I stumbled upon this [article](https://easycloudsupport.zendesk.com/hc/en-us/articles/360036344132-AWS-How-do-I-remove-the-throttle-on-port-25-from-my-EC2-instance-) which links to a form where you can request to remove the port 25 limitations placed upon EC2 instances.
