### ISSUE TITLE
How to migrate from other mailservers

### ISSUE THREAD

**Issue by ms747** [LukeSmithxyz/emailwiz#36]
Currently I'm using gmail. How do I import all my previous emails from gmail ? Thanks

**Comment by Jaapk** [comment]
I used isync to fetch the mailbox from my old server, Luke has some nice postings on this tool. Would be nice to have it scripted though.

**Comment by LukeSmithxyz** [comment]
Yes, use isync/mbsync: https://www.youtube.com/watch?v=tR9zk3xz5SA

Emails are just files. Now that you have direct access to your mail in a server, you can move them around like normal files.
