### ISSUE TITLE
What does the -f flag do for spamc?

### ISSUE THREAD

**Issue by edwargix** [LukeSmithxyz/emailwiz#4]
I can't find the `-f` flag in the `spamc` man page
https://github.com/LukeSmithxyz/emailwiz/blob/493fbd2f73d056ab61fb66b92daf5e2c842d6fb7/emailwiz.sh#L74

**Comment by tluszcz** [comment]
> **-f** 
> Cause spamc to safe-failover if it can't connect to spamd -- what this means is that in case spamc fails to connect to spamd, it will not return with an exitcode set, it will instead dump the original message to stdout, allowing the message to be delivered, albeit unscanned for spam. Without this flag, connection failures to spamd will cause message delivery failures.
> 
> Even with this flag set however, if spamc connects successfully, and then encounters an error at a later stage of communication, it will still return an exitcode.
> 
> This now defaults to on. This flag is accepted though for backwards-compatibility. -x can be used to tell spamc to use an exit-code which will cause the message to be re-queued by the MTA instead.

From [here](https://spamassassin.apache.org/full/2.6x/dist/doc/spamc.html)
