### ISSUE TITLE
Configure rDNS

### ISSUE THREAD

**Issue by s0m3OnE47** [LukeSmithxyz/emailwiz#40]
I checked my domain with different email tester and everything looks fine. But still my emails are going to spam (atleast on gmail). I have waited for a week so that domain name gets cleared from spam blacklist.

Upon testing on https://www.mail-tester.com It says:
Delivered to internal network by a host with no rDNS
This may indicate you do not have a rDNS configured for your hostname or the rDNS does not match your sending IP

I same setup as unaboomer.com

**Comment by AlexBocken** [comment]
I seem to have the same issue.
I'm not sure if rDNS is the issue, for me NameSMTP Banner Check is also failing when i use mxtoolbox.com. (port 25 is open for me)
Does the banner check work for you?

**Comment by aoutabounte** [comment]
I have the same issue, and the only problem I think is rDNS not being configured, not really sure how to do it.
![pic-selected-200628-1057-27](https://user-images.githubusercontent.com/66022183/85944413-6efe1180-b92e-11ea-91ce-69d0ca2ab830.png)
this photo is from [https://www.mail-tester.com/](url)

**Comment by cckuan2718** [comment]
Reverse DNS can be set in vultr's setting panel(or contact your ISP).

**Comment by aoutabounte** [comment]
> Reverse DNS can be set in vultr's setting panel(or contact your ISP).

Yes, thank you, I think that solves the problem. It should be so when you `nslookup "ip-address"` on any machine it answers by `name = domain.xyz.` and not the generic `"ip-address.vultr.com"`

**Comment by AlexBocken** [comment]
Thank you @cckuan2718 !
To add to this, I was getting and invalid SMTP hostname if i entered just my domain on vultr.
If you want to have everything set correctly, use `mail.domain.xyz`, not just `domain,xyz` for the reverse DNS.

**Comment by aoutabounte** [comment]
> Thank you @cckuan2718 !
> To add to this, I was getting and invalid SMTP hostname if i entered just my domain on vultr.
> If you want to have everything set correctly, use `mail.domain.xyz`, not just `domain.xyz` for the reverse DNS.

no no no, you need to put `domain.xyz.` for the rDNS (make sure to add the trailing period.)
rDNS is for your whole domain and not just `mail`

**Comment by AlexBocken** [comment]
> > Thank you @cckuan2718 !
> > To add to this, I was getting and invalid SMTP hostname if i entered just my domain on vultr.
> > If you want to have everything set correctly, use `mail.domain.xyz`, not just `domain.xyz` for the reverse DNS.
> 
> no no no, you need to put `domain.xyz.` for the rDNS (make sure to add the trailing period.)
> rDNS is for your whole domain and not just `mail`

If I do that mxtoolbox.com claims that I have an invalid SMTP Hostname though.
Am I just missing something?

**Comment by s0m3OnE47** [comment]
I did mail.domain.xyz in rDNS, now I am getting 10/10 on mail-tester.com, but still my mails are going to spam

**Comment by AlexBocken** [comment]
Did you check whether your domain is on a blacklist? Luke has provided a link to check hat at the bottom of the Readme.

**Comment by s0m3OnE47** [comment]
No blacklist but 1 timeout: NoSolicitado

**Comment by AlexBocken** [comment]
I think that shouldn't be an issue, I also had that from time to time. I'm at the end of my limited knowledge, so maybe someone else can help you. Maybe create a seperate issue, as it's not technically about rDNS anymore?

**Comment by s0m3OnE47** [comment]
Okay. 
I used this for rDNS.
> 
> 
> Thank you @cckuan2718 !
> To add to this, I was getting and invalid SMTP hostname if i entered just my domain on vultr.
> If you want to have everything set correctly, use `mail.domain.xyz`, not just `domain.xyz` for the reverse DNS.
Would this be the issue for going to spam?

**Comment by AlexBocken** [comment]
For me it goes to spam when I use `domain.xyz.` but get's through if I use `mail.domain.xyz`. I think rDNS should be fine if mail-tester.com and/or mxtoolbox.com don't give a warning for those areas.
I don't think this is some weird quirk of mine since I'm using a pretty basic setup and just followed Luke's tutorial.
Have you tried it with another gmail account? Maybe gmail is weird and still distrusts you because earlier emails weren't trustworthy (just a guess tbh)

**Comment by s0m3OnE47** [comment]
[These are the warning that I got:](https://imgur.com/a/SjNmIm4)
DMARC Quarantine/Reject policy not enabled 
Name Servers are on the Same Subnet 
SOA Expire Value out of recommended range
