### ISSUE TITLE
DKIM permerror

### ISSUE THREAD

**Issue by fretzak124** [LukeSmithxyz/emailwiz#41]
When sending mail to Gmail it gets put into spam and when I test it using the appmaildev site it says this: "DKIM-Result: permerror (no key)".
I double checked all the TXT entries and everything seems to be fine there.

**Comment by cckuan2718** [comment]
Can you post your /var/log/maillog?
find opendkim in the log( grep opendkim /var/log/maillog ).

**Comment by fretzak124** [comment]
This is what it reads.
root@mail:~# grep opendkim /var/log/mail.log
Jun 28 10:12:07 guest opendkim[4616]: OpenDKIM Filter v2.11.0 starting (args: -x /etc/opendkim.conf)
Jun 28 10:13:02 mail opendkim[4616]: OpenDKIM Filter: mi_stop=1
Jun 28 10:13:02 mail opendkim[4616]: OpenDKIM Filter v2.11.0 terminating with status 0, errno = 0
Jun 28 10:13:02 mail opendkim[14414]: OpenDKIM Filter v2.11.0 starting (args: -x /etc/opendkim.conf)

**Comment by cckuan2718** [comment]
Maybe sent a message out and try grep mail log again?

**Comment by fretzak124** [comment]
Hmmm it prints out the same thing still.

**Comment by s0m3OnE47** [comment]
This solved the issue for me

https://github.com/LukeSmithxyz/emailwiz/issues/18

**Comment by fretzak124** [comment]
I already tried adding the sha256 before to the TXT entry but it doesnt't change anything for me.

**Comment by fretzak124** [comment]
Thanks for trying to help though.

**Comment by s0m3OnE47** [comment]
use this for TXT record and remove quotation marks
cat /etc/postfix/dkim/mail.txt
https://github.com/LukeSmithxyz/emailwiz/issues/18#issue-629599333

**Comment by fretzak124** [comment]
It seems like even after doing this, I get the same error. I'm very sorry if I'm doing something wrong.

**Comment by fretzak124** [comment]
The problem doesnt't seem to be with the DNS records I think. When looking at the mail.log file, opendkim doesnt't seem to log anything whenever I send mail leading me to think that the problem lies with opendkim itself.

**Comment by tole-stoy** [comment]
I am having similar issues as well. I copied the same hash with the h=sha256 option but during the test it results in `DKIM-Result: permerror (no key)`. The log show opendkim starting and seemingly some links with google. The emails go to spam when I send one to a gmail. Can someone help me?
