### ISSUE TITLE
OpenDKIM milter socket issues on ubuntu 2004

### ISSUE THREAD

**Issue by mandatoryoption** [LukeSmithxyz/emailwiz#42]
Fresh vultr ubtuntu instance. When running the script the opendkim service fails to start. 

journalctl gives: `systemd[1]: Failed to start OpenDKIM DomainKeys Identified Mail (DKIM) Milter.`

Mail.log shows:
```
Jun 28 18:40:40 guest opendkim[18528]: OpenDKIM Filter v2.11.0 starting (args: -x /etc/opendkim.conf)
Jun 28 18:41:35 opendkim[18528]: OpenDKIM Filter v2.11.0 terminating with status 0, errno = 0
Jun 28 18:56:13 opendkim[1669]: OpenDKIM Filter: unknown socket type smtp
Jun 28 18:56:13 opendkim[1669]: OpenDKIM Filter: Unable to create listening socket on conn smtp
Jun 28 18:56:13 opendkim[1669]: smfi_opensocket() failed
```

I attempted to manually add the socket `inet:12301@localhost` to the opendkim config since it seems to me as though the sed command in the script is not applying it as expected. I dont know enough about this to know how or why, just a shot in the dark.

It all works after adding the socket to the opendkim configuration manually.

**Comment by user234683** [comment]
See [this comment](https://github.com/LukeSmithxyz/emailwiz/issues/20#issuecomment-652684376) for more detailed steps. I'm also using Ubuntu 20.04 x64.
