### ISSUE TITLE
Cannot send email Debian VPS

### ISSUE THREAD

**Issue by yusufbaylav** [LukeSmithxyz/emailwiz#44]
Although I have done the settings according to the video, I can receive email but cannot send. Not only to gmail but also other emails.
* In the journalctl -xe it is saying time out.
* at a point I saw  TLS library problem: error:1408A0C1  

What steps should I follow? Have no problem with receiving mail.

**Comment by s0m3OnE47** [comment]
Reffer this
https://github.com/LukeSmithxyz/emailwiz/issues/23

https://github.com/LukeSmithxyz/emailwiz/issues/21

You need to contact vultr and request that port 25 be unblocked.

**Comment by yusufbaylav** [comment]
I have created a ticket regarding this, thanks for your help.
