### ISSUE TITLE
Can't connect to the mail server

### ISSUE THREAD

**Issue by Nedimko123** [LukeSmithxyz/emailwiz#46]
I've installed the script on a fresh debian 10 server ( after I installed the web server domain, like you), now everything works with sendmail, if I send mail to gmail it arrives in the inbox without getting marked as spam, but I cannot connect to my mail via Mozilla Thunderbird or any other software. Tried every single port and ssl setting, checked netstat to see if it was listening, and it was listening on right ports... The installation went without any errors, so I don't know...

**Comment by elleven11** [comment]
are you using linode? https://www.linode.com/blog/linode/a-new-policy-to-help-fight-spam/
if so you will need to send a ticket.
also other providers have that problem, i found mine here: https://support.plesk.com/hc/en-us/articles/213394989--Unable-to-send-emails-using-Plesk-local-mail-server-Connection-timed-out-or-connection-refused-4-4-1-

**Comment by Nedimko123** [comment]
> are you using linode? https://www.linode.com/blog/linode/a-new-policy-to-help-fight-spam/
> if so you will need to send a ticket.
> also other providers have that problem, i found mine here: https://support.plesk.com/hc/en-us/articles/213394989--Unable-to-send-emails-using-Plesk-local-mail-server-Connection-timed-out-or-connection-refused-4-4-1-

No, sir. I am using https://www.hetzner.com/cloud Hetzner Cloud.

Here is what mail.log shows:
`Jul  1 22:38:26 postfix dovecot: imap-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=192.35.168.211, lip=116.203.177.204, TLS: Connection closed, session=<lLcbRmeppoTAI6jT>
Jul  1 23:07:47 postfix postfix/smtpd[29729]: connect from sh-ams-nl-gp1-wk113.internet-census.org[107.6.183.162]
Jul  1 23:07:47 postfix postfix/smtpd[29729]: disconnect from sh-ams-nl-gp1-wk113.internet-census.org[107.6.183.162] ehlo=1 quit=1 commands=2
Jul  1 23:07:47 postfix postfix/smtpd[29729]: connect from sh-ams-nl-gp1-wk113.internet-census.org[107.6.183.162]
Jul  1 23:07:47 postfix postfix/smtpd[29729]: disconnect from sh-ams-nl-gp1-wk113.internet-census.org[107.6.183.162] ehlo=1 starttls=1 quit=1 commands=3
Jul  1 23:07:47 postfix postfix/smtpd[29729]: connect from sh-ams-nl-gp1-wk113.internet-census.org[107.6.183.162]
Jul  1 23:07:47 postfix postfix/smtpd[29729]: disconnect from sh-ams-nl-gp1-wk113.internet-census.org[107.6.183.162] ehlo=1 starttls=1 quit=1 commands=3
Jul  1 23:07:47 postfix postfix/smtpd[29729]: connect from sh-ams-nl-gp1-wk113.internet-census.org[107.6.183.162]
Jul  1 23:07:47 postfix postfix/smtpd[29729]: SSL_accept error from sh-ams-nl-gp1-wk113.internet-census.org[107.6.183.162]: -1
Jul  1 23:07:47 postfix postfix/smtpd[29729]: warning: TLS library problem: error:1420918C:SSL routines:tls_early_post_process_client_hello:version too low:../ssl/statem/statem_srvr.c:1686:
Jul  1 23:07:47 postfix postfix/smtpd[29729]: lost connection after STARTTLS from sh-ams-nl-gp1-wk113.internet-census.org[107.6.183.162]
Jul  1 23:07:47 postfix postfix/smtpd[29729]: disconnect from sh-ams-nl-gp1-wk113.internet-census.org[107.6.183.162] ehlo=1 starttls=0/1 commands=1/2
Jul  1 23:07:54 postfix postfix/smtpd[29729]: connect from sh-ams-nl-gp1-wk113.internet-census.org[107.6.183.162]
Jul  1 23:07:55 postfix postfix/smtpd[29729]: disconnect from sh-ams-nl-gp1-wk113.internet-census.org[107.6.183.162] ehlo=1 starttls=1 quit=1 commands=3
Jul  1 23:07:55 postfix postfix/smtpd[29729]: connect from sh-ams-nl-gp1-wk113.internet-census.org[107.6.183.162]
Jul  1 23:07:55 postfix postfix/smtpd[29729]: disconnect from sh-ams-nl-gp1-wk113.internet-census.org[107.6.183.162] ehlo=1 starttls=1 quit=1 commands=3
Jul  1 23:11:15 postfix postfix/anvil[29731]: statistics: max connection rate 6/60s for (smtp:107.6.183.162) at Jul  1 23:07:55
Jul  1 23:11:15 postfix postfix/anvil[29731]: statistics: max connection count 1 for (smtp:107.6.183.162) at Jul  1 23:07:47
Jul  1 23:11:15 postfix postfix/anvil[29731]: statistics: max cache size 1 at Jul  1 23:07:47
Jul  1 23:51:04 postfix dovecot: imap-login: Disconnected (no auth attempts in 7 secs): user=<>, rip=106.75.189.104, lip=116.203.177.204, TLS: Connection closed, session=<8eDVSWipHMhqS71o>
Jul  2 02:12:29 postfix dovecot: imap-login: Disconnected (no auth attempts in 1 secs): user=<>, rip=185.153.199.12, lip=116.203.177.204, session=<TYaYQ2qpAv65mccM>
Jul  2 04:13:46 postfix postfix/submission/smtpd[4593]: connect from burger.census.shodan.io[66.240.219.146]
Jul  2 04:14:02 postfix postfix/submission/smtpd[4603]: connect from burger.census.shodan.io[66.240.219.146]
Jul  2 04:14:02 postfix postfix/submission/smtpd[4593]: lost connection after STARTTLS from burger.census.shodan.io[66.240.219.146]
Jul  2 04:14:02 postfix postfix/submission/smtpd[4593]: disconnect from burger.census.shodan.io[66.240.219.146] ehlo=1 starttls=1 commands=2
Jul  2 04:14:03 postfix postfix/submission/smtpd[4603]: lost connection after STARTTLS from burger.census.shodan.io[66.240.219.146]
Jul  2 04:14:03 postfix postfix/submission/smtpd[4603]: disconnect from burger.census.shodan.io[66.240.219.146] ehlo=1 starttls=1 commands=2
Jul  2 04:14:05 postfix postfix/submission/smtpd[4593]: connect from burger.census.shodan.io[66.240.219.146]
Jul  2 04:14:05 postfix postfix/submission/smtpd[4593]: SSL_accept error from burger.census.shodan.io[66.240.219.146]: -1
Jul  2 04:14:05 postfix postfix/submission/smtpd[4593]: warning: TLS library problem: error:142090FC:SSL routines:tls_early_post_process_client_hello:unknown protocol:../ssl/statem/statem_srvr.c:1661:
Jul  2 04:14:05 postfix postfix/submission/smtpd[4593]: lost connection after STARTTLS from burger.census.shodan.io[66.240.219.146]
Jul  2 04:14:05 postfix postfix/submission/smtpd[4593]: disconnect from burger.census.shodan.io[66.240.219.146] ehlo=1 starttls=0/1 commands=1/2
Jul  2 04:14:07 postfix postfix/submission/smtpd[4603]: connect from burger.census.shodan.io[66.240.219.146]
Jul  2 04:14:07 postfix postfix/submission/smtpd[4603]: SSL_accept error from burger.census.shodan.io[66.240.219.146]: -1
Jul  2 04:14:07 postfix postfix/submission/smtpd[4603]: warning: TLS library problem: error:1420918C:SSL routines:tls_early_post_process_client_hello:version too low:../ssl/statem/statem_srvr.c:1686:
Jul  2 04:14:07 postfix postfix/submission/smtpd[4603]: lost connection after STARTTLS from burger.census.shodan.io[66.240.219.146]
Jul  2 04:14:07 postfix postfix/submission/smtpd[4603]: disconnect from burger.census.shodan.io[66.240.219.146] ehlo=1 starttls=0/1 commands=1/2
Jul  2 04:14:09 postfix postfix/submission/smtpd[4593]: connect from burger.census.shodan.io[66.240.219.146]
Jul  2 04:14:09 postfix postfix/submission/smtpd[4593]: lost connection after STARTTLS from burger.census.shodan.io[66.240.219.146]
Jul  2 04:14:09 postfix postfix/submission/smtpd[4593]: disconnect from burger.census.shodan.io[66.240.219.146] ehlo=1 starttls=1 commands=2
Jul  2 04:14:10 postfix postfix/submission/smtpd[4603]: connect from burger.census.shodan.io[66.240.219.146]
Jul  2 04:14:11 postfix postfix/submission/smtpd[4603]: lost connection after STARTTLS from burger.census.shodan.io[66.240.219.146]
Jul  2 04:14:11 postfix postfix/submission/smtpd[4603]: disconnect from burger.census.shodan.io[66.240.219.146] ehlo=1 starttls=1 commands=2
Jul  2 04:14:12 postfix postfix/submission/smtpd[4593]: connect from burger.census.shodan.io[66.240.219.146]
Jul  2 04:14:12 postfix postfix/submission/smtpd[4593]: lost connection after CONNECT from burger.census.shodan.io[66.240.219.146]
Jul  2 04:14:12 postfix postfix/submission/smtpd[4593]: disconnect from burger.census.shodan.io[66.240.219.146] commands=0/0
Jul  2 04:14:17 postfix postfix/submission/smtpd[4603]: connect from burger.census.shodan.io[66.240.219.146]
Jul  2 04:14:18 postfix postfix/submission/smtpd[4603]: lost connection after STARTTLS from burger.census.shodan.io[66.240.219.146]
Jul  2 04:14:18 postfix postfix/submission/smtpd[4603]: disconnect from burger.census.shodan.io[66.240.219.146] ehlo=1 starttls=1 commands=2
Jul  2 04:14:26 postfix postfix/submission/smtpd[4593]: connect from burger.census.shodan.io[66.240.219.146]
Jul  2 04:14:26 postfix postfix/submission/smtpd[4593]: lost connection after CONNECT from burger.census.shodan.io[66.240.219.146]
Jul  2 04:14:26 postfix postfix/submission/smtpd[4593]: disconnect from burger.census.shodan.io[66.240.219.146] commands=0/0
Jul  2 04:14:42 postfix postfix/submission/smtpd[4603]: connect from burger.census.shodan.io[66.240.219.146]
Jul  2 04:14:47 postfix postfix/submission/smtpd[4603]: lost connection after CONNECT from burger.census.shodan.io[66.240.219.146]
Jul  2 04:14:47 postfix postfix/submission/smtpd[4603]: disconnect from burger.census.shodan.io[66.240.219.146] commands=0/0
Jul  2 04:18:07 postfix postfix/anvil[4595]: statistics: max connection rate 10/60s for (submission:66.240.219.146) at Jul  2 04:14:42
Jul  2 04:18:07 postfix postfix/anvil[4595]: statistics: max connection count 2 for (submission:66.240.219.146) at Jul  2 04:14:02
Jul  2 04:18:07 postfix postfix/anvil[4595]: statistics: max cache size 1 at Jul  2 04:13:46
Jul  2 04:29:29 postfix postfix/smtpd[4960]: connect from unknown[185.234.216.140]
Jul  2 04:29:29 postfix postfix/smtpd[4960]: disconnect from unknown[185.234.216.140] ehlo=1 auth=0/1 rset=1 quit=1 commands=3/4
Jul  2 04:32:49 postfix postfix/anvil[4962]: statistics: max connection rate 1/60s for (smtp:185.234.216.140) at Jul  2 04:29:29
Jul  2 04:32:49 postfix postfix/anvil[4962]: statistics: max connection count 1 for (smtp:185.234.216.140) at Jul  2 04:29:29
Jul  2 04:32:49 postfix postfix/anvil[4962]: statistics: max cache size 1 at Jul  2 04:29:29
Jul  2 06:29:42 postfix postfix/smtpd[9138]: warning: hostname zg-0626-344.stretchoid.com does not resolve to address 162.243.132.230: Name or service not known
Jul  2 06:29:42 postfix postfix/smtpd[9138]: connect from unknown[162.243.132.230]
Jul  2 06:29:42 postfix postfix/smtpd[9138]: disconnect from unknown[162.243.132.230] ehlo=1 quit=1 commands=2
Jul  2 06:33:02 postfix postfix/anvil[9140]: statistics: max connection rate 1/60s for (smtp:162.243.132.230) at Jul  2 06:29:42
Jul  2 06:33:02 postfix postfix/anvil[9140]: statistics: max connection count 1 for (smtp:162.243.132.230) at Jul  2 06:29:42
Jul  2 06:33:02 postfix postfix/anvil[9140]: statistics: max cache size 1 at Jul  2 06:29:42
Jul  2 07:09:28 postfix postfix/smtpd[10657]: connect from 30.20.97.83.ro.ovo.sc[83.97.20.30]
Jul  2 07:09:58 postfix postfix/smtpd[10657]: lost connection after CONNECT from 30.20.97.83.ro.ovo.sc[83.97.20.30]
Jul  2 07:09:58 postfix postfix/smtpd[10657]: disconnect from 30.20.97.83.ro.ovo.sc[83.97.20.30] commands=0/0
Jul  2 07:13:18 postfix postfix/anvil[10659]: statistics: max connection rate 1/60s for (smtp:83.97.20.30) at Jul  2 07:09:28
Jul  2 07:13:18 postfix postfix/anvil[10659]: statistics: max connection count 1 for (smtp:83.97.20.30) at Jul  2 07:09:28
Jul  2 07:13:18 postfix postfix/anvil[10659]: statistics: max cache size 1 at Jul  2 07:09:28
Jul  2 07:56:31 postfix postfix/smtps/smtpd[11999]: warning: hostname zg-0626a-352.stretchoid.com does not resolve to address 192.241.224.137: Name or service not known
Jul  2 07:56:31 postfix postfix/smtps/smtpd[11999]: connect from unknown[192.241.224.137]
Jul  2 07:56:31 postfix postfix/smtps/smtpd[11999]: SSL_accept error from unknown[192.241.224.137]: -1
Jul  2 07:56:31 postfix postfix/smtps/smtpd[11999]: warning: TLS library problem: error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:332:
Jul  2 07:56:31 postfix postfix/smtps/smtpd[11999]: lost connection after CONNECT from unknown[192.241.224.137]
Jul  2 07:56:31 postfix postfix/smtps/smtpd[11999]: disconnect from unknown[192.241.224.137] commands=0/0
Jul  2 08:12:57 postfix postfix/submission/smtpd[12604]: warning: hostname zg-0626a-220.stretchoid.com does not resolve to address 192.241.221.125: Name or service not known
Jul  2 08:12:57 postfix postfix/submission/smtpd[12604]: connect from unknown[192.241.221.125]
Jul  2 08:12:57 postfix postfix/submission/smtpd[12604]: disconnect from unknown[192.241.221.125] ehlo=1 quit=1 commands=2
Jul  2 08:16:17 postfix postfix/anvil[12606]: statistics: max connection rate 1/60s for (submission:192.241.221.125) at Jul  2 08:12:57
Jul  2 08:16:17 postfix postfix/anvil[12606]: statistics: max connection count 1 for (submission:192.241.221.125) at Jul  2 08:12:57
Jul  2 08:16:17 postfix postfix/anvil[12606]: statistics: max cache size 1 at Jul  2 08:12:57
Jul  2 08:18:40 postfix postfix/smtpd[12697]: connect from unknown[185.234.216.140]
Jul  2 08:18:40 postfix postfix/smtpd[12697]: disconnect from unknown[185.234.216.140] ehlo=1 auth=0/1 rset=1 quit=1 commands=3/4
Jul  2 08:22:00 postfix postfix/anvil[12699]: statistics: max connection rate 1/60s for (smtp:185.234.216.140) at Jul  2 08:18:40
Jul  2 08:22:00 postfix postfix/anvil[12699]: statistics: max connection count 1 for (smtp:185.234.216.140) at Jul  2 08:18:40
Jul  2 08:22:00 postfix postfix/anvil[12699]: statistics: max cache size 1 at Jul  2 08:18:40
Jul  2 09:09:56 postfix postfix/smtpd[14105]: connect from unknown[46.38.150.47]
Jul  2 09:09:57 postfix postfix/smtpd[14105]: disconnect from unknown[46.38.150.47] ehlo=1 auth=0/1 rset=1 quit=1 commands=3/4
Jul  2 09:13:18 postfix postfix/anvil[14107]: statistics: max connection rate 1/60s for (smtp:46.38.150.47) at Jul  2 09:09:56
Jul  2 09:13:18 postfix postfix/anvil[14107]: statistics: max connection count 1 for (smtp:46.38.150.47) at Jul  2 09:09:56
Jul  2 09:13:18 postfix postfix/anvil[14107]: statistics: max cache size 1 at Jul  2 09:09:56
Jul  2 09:16:51 postfix dovecot: imap-login: Disconnected (no auth attempts in 10 secs): user=<>, rip=192.241.215.100, lip=116.203.177.204, session=<nrRAMXCpWJjA8ddk>
Jul  2 09:52:25 postfix dovecot: imap-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=185.153.199.12, lip=116.203.177.204, session=<8YR1sHCpMUe5mccM>
Jul  2 10:06:41 postfix postfix/smtpd[15276]: connect from unknown[71.6.232.5]
Jul  2 10:06:41 postfix postfix/smtpd[15276]: disconnect from unknown[71.6.232.5] ehlo=1 quit=1 commands=2
Jul  2 10:10:02 postfix postfix/anvil[15278]: statistics: max connection rate 1/60s for (smtp:71.6.232.5) at Jul  2 10:06:41
Jul  2 10:10:02 postfix postfix/anvil[15278]: statistics: max connection count 1 for (smtp:71.6.232.5) at Jul  2 10:06:41
Jul  2 10:10:02 postfix postfix/anvil[15278]: statistics: max cache size 1 at Jul  2 10:06:41
`

**Comment by mindofmateo** [comment]
I am also having the same issue mentioned in the first comment.  I followed Luke's instructions, but using Thunderbird just to verify it is up and running, it always says "Thunderbird failed to find the settings for your email account."

**Comment by andrewrunxiyu** [comment]
Looking at your logs, it seems that either thunderbird is having a problem itself or your provider blocks port 993 (Yes, port 993 not anything else). I would suggest you try it out with another email client, say, neomutt, and try again. 
If it is a thunderbird problem, carefully check your configs: Servers are probably mail.*.*, imap port 993 smtp port 597, imap authentication automatic, imap encryption SSL/TLS.
