### ISSUE TITLE
IPV6 and SPF

### ISSUE THREAD

**Issue by nebulaw2081d** [LukeSmithxyz/emailwiz#48]
I have recently encountered an issue with the emailwiz script, but I believe this could apply to many different mail setups. Suppose I have the domain "example.com" with the following DNS records:

mail.example.com                A          123.456.789.10
@                                                 SPF       v=spf1 mx a:mail.example.com -all
@                                                 MX        mail.example.com

In most setups this should be fine, however for mail servers where "mail.example.com" might be resolved to IPV6, the SPF verification will fail, potentially resulting in an issue where mail is placed in spam or not sent at all.

I recently discovered this issue when sending to a "gmail.com" address. The issue was resolved by creating an AAAA record as such:

mail.example.com              AAAA     1234:5678::910a:bcde:f123:4567

As this isn't an issue specifically with emailwiz, I'm not sure if any changes should be made, but potentially some type of notice near the conclusion of the script so people may make the following changes.

**Comment by LukeSmithxyz** [comment]
I might make a note of this in the README because I'm sure it's overlooked, but it is sort of something that should be expected if you're setting up any website with IPv6.

Of course I say that, but I know for a fact that the LARBS website's IPv6 has been screwed up for a while (lol).
