### ISSUE TITLE
Curl Error

### ISSUE THREAD

**Issue by cemkeylan** [LukeSmithxyz/emailwiz#5]
When you execute the curl command on the README.md file,

`curl -LO lukesmith.xyz/emailwiz.sh`

It returns "404: Not Found"

You said 

> on my LARBS.xyz domain

so I tried "larbs.xyz/emailwiz.sh", but that downloaded the html code of larbs.xyz.

**Comment by LukeSmithxyz** [comment]
This was my mistake when I updated my website a couple minutes ago. I've fixed the links now.
