### ISSUE TITLE
Can't add @ as hostname for TXT entry on Linode.

### ISSUE THREAD

**Issue by QPO-LordCyrus** [LukeSmithxyz/emailwiz#54]
Does anybody have any experience making this work on Linode, I can't add the @ to the TXT it says: "Name contains invalid characters"...

Also when I try to login I get: <a href="https://ibb.co/DKZrs6S"><img src="https://i.ibb.co/nkFPZV5/fail.png" alt="fail" border="0"></a>

I humbly request your guidance.

**Comment by Abdulee** [comment]
the @ entry i think means your domain name basically. So you can just type it instead in your case I think it would be cyxstudios.com
