### ISSUE TITLE
Unable to receive any mail

### ISSUE THREAD

**Issue by Abdulee** [LukeSmithxyz/emailwiz#57]
Hello set up everything got DKIM working able to send mails to gmail inboxes no spam or anything but unable to receive mails. I followed all steps in the video now however I dont have any mails received when i send them from my other email address. 
Also one thing to know when I send from the same email server for example ted@mydomain.com to billy@mydomain.com this is the message which thunderbird returns ```An error occurred while sending mail. The mail server responded:
451 4.3.0 <billy@mydomain.com>: Temporary lookup failure.
Please check the message recipient "billy@mydomain.com" and try again.```

Any help massively appreciated I am very noob so if I made an oopsie I hope you can point it out. Thank u

**Comment by jrejaud** [comment]
I've running into this issue as well, can you elaborate if you were able to resolve it?
