### ISSUE TITLE
No SPF or DMARC

### ISSUE THREAD

**Issue by majestrate** [LukeSmithxyz/emailwiz#6]
these scripts should also handle SPF and possibly also DMARC

https://en.wikipedia.org/wiki/Sender_Policy_Framework
https://en.wikipedia.org/wiki/DMARC

**Comment by LukeSmithxyz** [comment]
I was going to add DMARC today. I don't know if you have any recommendations for this (reject vs. quarantine, etc.).

I was probably just going to have the wizard create a dummy dmarc account mail to send the reports to. I still am figuring out the specifcs.

**Comment by LukeSmithxyz** [comment]
Closing this because I've added DMARC and checked that it works.
