### ISSUE TITLE
Cannot send emails (how to fix)

### ISSUE THREAD

**Issue by lifecycletest** [LukeSmithxyz/emailwiz#60]
I followed his instructions (vultr server) with the exception that Namecheap has my DNS name.  Everything went smoothly and I could receive emails, but not send them.  Here's what I had to do to get it working:

1 - After debugging it for a while I noticed in the "journalctl -xe" output a line:

    postfix/smtp[1263]: connect bla bla :25: Connection Timed Out

  I then checked port 25 using "telnet google.com 25" and it was blocked.  I had to put in a ticket to prove to them I was not a Chinese spammer and they unlocked it and everything worked perfectly.

2 - When I was debugging the problem with online MX record testers, they complained about the "CNAME" records he used in the video.  Apparently there is some RFC-66613... spec that wants ANAME records.  The difference between the CNAME and ANAME, is the ANAME points to your numeric IP address and the CNAME is an alias to your hostname which points to your numeric IP.  I don't think the CNAME records were the problem, but whatever, the fix was just some cut and paste.

3 - His GIT readme mentions that you need to set your reverse domain name in the vultr control panel.  The test sites did not like "mydomain.wtf", but wanted it to be "mail.mydomain.wtf"

I made the switch because Gmail was blocking my Huawei developer emails (gee I wonder why).  They have AI spying on everything you do now, so disconnect from the Borg net while you still can, and support master Luke because you know sooner or later they will take him down to :(

**Comment by alpha-tango-kilo** [comment]
@lifecycletest for (1), where did you have to put in a ticket? Also experiencing the same issue
