### ISSUE TITLE
SpamAssasin not making mail go to junk

### ISSUE THREAD

**Issue by alanxyz** [LukeSmithxyz/emailwiz#61]
I was having issues with setting up a Patreon account as I was not getting the mail. I did customer support and they told me my mail server was hard bouncing. I disabled Spamassassin and I did not have the issue anymore. Shouldn't spam assassin be making the mail go to the junk folder? 
Apologies if this was covered in another issue, but I couldn't find one related to this.

**Comment by cckuan2718** [comment]
Can you post your `/var/log/maillog` related to the specific patreon mail?
