### ISSUE TITLE
When connecting from Thunderbird it fails the first time and succeeds the second.

### ISSUE THREAD

**Issue by vicenteferrari** [LukeSmithxyz/emailwiz#64]
Right after installing the script I tried connecting with Thunderbird. When you put in your info and tries to autodetect it works fine (though when I close the non-TLS ports it doesn't auto detect correctly) but the first time it tries to connect it fails. The second time though which happens right after, connects fine. Very weird. My latency to the server is ~140ms.

**Comment by LukeSmithxyz** [comment]
I've noticed this too. It happened in the video I did on this in fact. Not sure what causes this exactly and I think it's just with Thunderbird's default settings, whatever they are.
