### ISSUE TITLE
Can't Connect thunderbird to email server, but I can send it emails

### ISSUE THREAD

**Issue by Kaddu720** [LukeSmithxyz/emailwiz#66]
I followed the video and used the script to try to set up my email server. I'm running Ubuntu 18 on a vultr compute instance. 

Upon finishing the configuration, I couldn't get Thunderbird to connect to the server. Even when I manually entered the IMAP and SMTP addresses and ports, I still got the "Thunderbird failed to find the settings for your email account" error. 

I then tried to send my server an email from a gmail account that I have, and the email went through. So, I can send mail to my server, but I can't log into it.

I'm wondering if there is an issue with my domain server. I'm using Amazon Route 53, but it has never given me any problems before. The only issue I can think of was that Amazon wouldn't let me create a CNAME for my mail server. So, I have 1 MX record named "mail.myserver.com" that points at "mail.myserver.com". And, I have an A record named "mail.myserver.com" that points directly at the IP address of my vultr server.

If there is anymore information that would help with the trouble shooting, just let me know.

**Comment by quisys** [comment]
did you fix it?
