### ISSUE TITLE
Using encrypted email storage - encfs?

### ISSUE THREAD

**Issue by FlyingKawasaki74** [LukeSmithxyz/emailwiz#67]
This is a noob question, but does anyone know what exactly the "encrypted email storage" is that some email providers boast about, and how to set it up on a VPS?

My guess is that they probably just encrypt their hard drives, but maybe it is possible to actually add another layer of encryption by encrypting the folders where emails are stored? I'd probably go with setting up encfs directories and (permanently) mounting them as root. However, I am no expert and don't know if that's a valid approach or if there is anything better.

**Comment by LukeSmithxyz** [comment]
Might depend on the service what they mean by it.

There is stuff like this:
https://doc.dovecot.org/configuration_manual/mail_crypt_plugin/

But I haven't really looked into it.
On 20/08/19 02:29AM, FlyingKawasaki74 wrote:
> This is a noob question, but does anyone know what exactly the "encrypted email storage" is that some email providers boast about, and how to set it up on a VPS?
>
> My guess is that they probably just encrypt their hard drives, but maybe it is possible to actually add another layer of encryption by encrypting the folders where emails are stored? I'd probably go with setting up encfs directories and (permanently) mounting them as root. However, I am no expert and don't know if that's a valid approach or if there is anything better.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/LukeSmithxyz/emailwiz/issues/67

--
https://lukesmith.xyz
