### ISSUE TITLE
Thunderbird won't connect to my server, and the read out from journalctl -xe makes not sense

### ISSUE THREAD

**Issue by Kaddu720** [LukeSmithxyz/emailwiz#68]
I ran the emailwiz script on my vultr server running ubuntu 18.04. The script appeared to have worked correctly. I can connect to the domain in my browser and cert bot is working properly. I successfully created a user in the mail group that has a strong password. 

When I look up my mail server with mxtoolbox, I get the correct response. The DNS and DMARC record both report being properly published.

 It does report that my DMARC policy is not enabled, but I assume that is caused by the script making p=none in my DMARC text record.

So, I t ran journalctl -xe to see what was going wrong. This is what is outputted:

postfix/submission/smtpd["a number"]: connect from unknown[ "my Ip address" ]
postfix/submission/smtpd["a number"]: lost connection after CONNECT from unknown[ "my Ip address" ]
postfix/submission/smtpd["a number"]: disconnect from unknown["my Ip address"]commands=0/0

Everything appears to be working properly, but when I try to connect to the server, it just looses my connection and disconnects. How can I solve this?

**Comment by Kaddu720** [comment]
When I first created the server I followed Luke's video about making a web server. In that video, he disabled logging in via password. I wonder if that's the issue.

**Comment by Kaddu720** [comment]
So I kept diggin around and I found that my server is giving a "454 4.7.1 relay access denied" error when I try to test it with MXTool box.

**Comment by Kaddu720** [comment]
I added a line of my etc/postfix/main.cf file

smtpd_recipient_restrictions = permit_sasl_authenticated , permit_mynetworks , reject_unauth_destination

Now it's giving me a 554 5.7.1 which I believe means that my server thinks incoming mail is spam. That's an improvement over thinking it's on a black list.

**Comment by Kaddu720** [comment]
So, I kept digging and I found that the error could be fixed by adding the following line to etc/postfix/main.cf: 
smtpd_recipient_restrictions =  permit_sasl_authenticated,  permit_mynetworks, reject_unauth_destination

Now, I'm getting another error when I ping my server from MXTools: 554 5.7.1
I think this might mean that my server is rejecting it, and by extension all mail, as spam

**Comment by minikN** [comment]
I have the exact same issue.
```
454 4.7.1 <test@mxtoolboxsmtpdiag.com>: Relay access denied [203 ms]
```

**Comment by minikN** [comment]
By the way, you can enable the DMARC policy by changing `p=none` to `p=quarantine` in your DNS record.

**Comment by minikN** [comment]
@Kaddu720 Have you found a solution?

**Comment by Kaddu720** [comment]
@minikN My solution was switching to debian, lol. Everything just works on Debian.

**Comment by minikN** [comment]
Haha, I like it! What version are you on?

**Comment by Kaddu720** [comment]
I'm on the newest version that vultr offers. I was to frustrated to actually check!

**Comment by minikN** [comment]
Just a FYI: Im still getting the same error when checking with mxtoolbox. Now on Debian 10. I am able to connect to my mailserver and send/receive mail (not through Thunderbird, but through my nextcloud mail app), however Gmail doesnt like my mailserver and marks it as spam, although my blacklist check on mxtoolbox shows Im not blacklisted anywhere.

Id still like to fix the `relay access denied` error and thr spam issue with gmail.

**Comment by Kaddu720** [comment]
@minikN 

If you're sending a receiving mail without any issue, I don't think you need to worry about the error. 

As for gmail, the issue is that Google has never heard of your domain. The only way to get it out of the spam folder is to send out a bunch of emails and have a bunch of people mark it as "not spam".
