### ISSUE TITLE
Port 25

### ISSUE THREAD

**Issue by deobbed** [LukeSmithxyz/emailwiz#70]
Does port 25 really need to be open? Can't you use 587? Since almost everyone is banning usage of port 25 due to security etc I would like to host it at home and not on Vultr since I can't really trust them. So as the opening line reads, Do I need port 25 open?

**Comment by egberts** [comment]
Port 25 does need to be open ... always.  

Port 587 is typically the port used for SMTP submissions by email clients. It usually uses TLS encryption as a security measure.

Port 25 is the universal port for email exchange between servers on the internet.

Email can be submitted via either port, in either an encrypted or unencrypted fashion, depending on your policy.

If you disable port 587, depending on your use case, you may actually be hurting your security by preventing an email client from communicating securely.

The proper action is to REQUIRE TLS(encrypted) connections on port 587, by changing your email server policies. This should satisfy the requirement, and eliminate the warning.

You should also support and allow TLS connections on port 25. Servers that support it will use it to deliver email securely. However, you can’t require it on port 25 as you will break the exchange of email.

Depending on your use case, you could potentially close port 587 if you do not have any clients or servers using the port to deliver email. This would be the case in something like an MS Exchange / Outlook setup that uses MAPI over HTTPS. But in almost every other type of email server setup, port 587 is used exclusively by the email client to submit secure emails to the server and obviously shouldn’t be closed.

Disclaimer: I host a secured email server (DMKI, SMTP server pointed to by DNSSEC DNS)

**Comment by Abdulee** [comment]
Yes port 25 is required and yes most ISP's will have it blocked. However, even if it is open most ISP's and home IP addresses are blacklisted and it is certain that even if your email is DKIM signed it will be filtered by spam filters and other mail servers who use an IP blocklist.
