### ISSUE TITLE
`mail.domain.tld` is not opening

### ISSUE THREAD

**Issue by acagastya** [LukeSmithxyz/emailwiz#74]
On Debian, after creating SSL certificates, I tried opening `mail.domain.tld` to get the `nginx` error, however, it does not load.  `domain.tld` seems to be working fine.

Any idea where I might be making a mistake?

**Comment by juandpineiro** [comment]
Check that you haven an A record pointing your `mail.domain.tld` to your server's IP address. I know that Luke created a CNAME record in his video, but that is not recommended. 

You can always check that the records are setup correctly using the `dig` command from another machine, for example:

```bash
$ dig yourdomain.tld a # Checks the A records on your domain name
...
;;ANSWER SECTION
;yourdomain.tld.    299    IN   A    <server-IP-address>
```
```bash

$ dig mail.yourdomain.tld a
...
;;ANSWER SECTION
;yourdomain.tld.    299    IN   A    <server-IP-address>
```
Hope this helps. Make sure you get a 404 trying to access mail.yourdomain.tld

**Comment by acagastya** [comment]
@juandpineiro I get the error saying `Records cannot share a name with a CNAME record.`  Should I delete the CNAME record in that case?

**Comment by juandpineiro** [comment]
@acagastya Yes. You should delete the CNAME and leave the A record.

**Comment by acagastya** [comment]
Despite using A records instead of CNAME, `mail.domail.tld` does not load.

And @juandpineiro, running dig gives:
```sh
dig domain.tld
...
;; ANSWER SECTION:
domail.tld.	252	IN	A	<server-ip-addr>
...
dig mail.domain.tld
...
;; ANSWER SECTION:
mail.domain.tld.	300	IN	A	<server-ip-addr>
...
```

**Comment by acagastya** [comment]
To clarify, the nginx error shows up before I run `certbot --nginx`.  After running it, it does not load.

**Comment by juandpineiro** [comment]
So, without the certificates can you access `mail.yourdomain.tld`? I mean, you get a 404? But not with the certificate? I would check opening the site on a new incognito window to see if it works. Also check the `/var/log/nginx/access.log` to see what's going on. I think you asked before about a firewall configuration? 

I have UFW installed on my server but it's currently disabled. If you are still in the nginx part you have to make sure ports 80 (http) and 443 (https) are open.

**Comment by acagastya** [comment]
I just did `ufw allow 80; ufw allow 443` and it works.  I can also log in to the mail via Thunderbird when I disable ufw.  Do you happen to know which ports do I need to allow for keeping the firewall and still logging in, @juandpineiro?

**Comment by acagastya** [comment]
I just enabled ports listed on `netstat -tulpn | grep LISTEN` and now it works fine.  Thanks, @juandpineiro!
