### ISSUE TITLE
Mail Still going to spam

### ISSUE THREAD

**Issue by jcrcx** [LukeSmithxyz/emailwiz#78]
Hi there,

I have configured a mail server in the past, and now is perfectly working (DKIM, DMARC, SPF, 10/10 [score](https://www.mail-tester.com/) , no more in spam on any mail service like google or hotmail, etc). But I've configured a second mail server exactly as the first one and I still going into spam on the big mail services. This also passes DKIM, DMARC, SPF. 

Thanks for any help :)

**Comment by jcrcx** [comment]
Solved.

Just added the directory `/var/www/mail`

**Comment by kushagraagent47** [comment]
Hey, can you give a bit clarity on how did you solve this?
