### ISSUE TITLE
Recieving mail at mail.domain.tld instead of domain.tld

### ISSUE THREAD

**Issue by lssjbrolly** [LukeSmithxyz/emailwiz#79]
I'm having an issue where I am able to send and receive mail no problem, however I'm unable to receive mail at domain.tld. Mail sends out fine, and I am able to login to smtp with domain.tld.

I have been able to modify the script on line 265 to make user@domain.tld work:
`postconf -e "myhostname = $domain"`
However, I'm worried that doing so might open myself up to being "spoofed" because my txt record is:
@       TXT     v=spf1 mx a:mail.domain.tld -all
This script worked great, which is why I'm wary of changing things in it. I would very much like to keep my smpt server to mail.domain.tld, I would just like my email to be delivered to user@domain.tld

**Comment by LukeSmithxyz** [comment]
What other settings had you changed in installation? By default you should be receiving mail at `account@domain.name` while both the IMAP and SMTP servers are at `mail.domain.name`.

**Comment by tzcrawford** [comment]
I don't know but I think it may have something to do with these options in `/etc/postfix/main.cf`. Here's what it looks like for me.
```
myhostname = mail.something.com
myorigin = /etc/mailname
mydestination = $myhostname, something.com, something.something.com, localhost.something.com, localhost
smtpd_tls_cert_file = /etc/letsencrypt/live/mail.something.com/fullchain.pem
smtpd_tls_key_file = /etc/letsencrypt/live/mail.something.com/privkey.pem
```
and for me,
```
$ cat /etc/mailname
something.com
```
