### ISSUE TITLE
Can't login on an android

### ISSUE THREAD

**Issue by Eddy-Arch** [LukeSmithxyz/emailwiz#80]
Logging and sending mail works just fine with Thunderbird on PC, but for some reason refuses to work on android (k9 mail) any reason as to why this might be? Could it be that I needed to add k9 as a trusted mail client or something of the sort?

**Comment by LukeSmithxyz** [comment]
If you put in all your server info properly, it should work without further changes. I use K-9 on a device without problem.

Remember to include a "login" of your name, rather than the full email address (luke instead of luke@larbs.xyz, e.g.).
