### ISSUE TITLE
Can't send email to web.de

### ISSUE THREAD

**Issue by ghost** [LukeSmithxyz/emailwiz#82]
I used this script and when I try to send an email to any @web.de address the Mail Delivery System returns an error. 
The Diagnostic-Code says: smtp; 550-Requested action not taken: mailbox unavailable 550 invalid DNS MX or A/AAAA resource record. I can send email to google though without any problems. Can someone who also used this script try sending an email to some web.de address to test if the same error occurs?

**Comment by tzcrawford** [comment]
I don't know the details, but perhaps you just need to wait a few hours for the DNS records to update and propagate? Or you don't have your domain records set up correctly?
