### ISSUE TITLE
Bad dovecot.conf file

### ISSUE THREAD

**Issue by zachspar** [LukeSmithxyz/emailwiz#83]
I royally messed up my email server lol. `emailwiz.sh` was working great for me until I had to renew my ssl certificates. Once I renewed them, my mail clients couldn't connect to the server any longer. I tried to reset everything from the beginning. I got rid of all my certs and re-certified my websites. Currently I am receiving an error: 
```dovecot[12534]: doveconf: Fatal: Error in configuration file /etc/dovecot/dovecot.conf line 10: ssl_cert: Can't open file /etc/dovecot/./fullchain.pem: No such file or directory```

It seems like the script put in a bad path into the `dovecot.conf` file and it is causing dovecot not to start. Maybe you have seen something like this before, and I am just too silly to figure it out.

**Comment by LukeSmithxyz** [comment]
It looks like the script ran without the `$certdir` variable set, which should be impossible since it's set earlier in the script.

You can just manually change it to the proper location that certbot has put your certificates. Somewhere in `/etc/letsencrypt/live/.......`

**Comment by zachspar** [comment]
So I figured out the issue and all is working now. The problem was that I had my both my mail and website certs combined, so when the script did `$certdir` it was grabbing the base domain. Thanks for the help, and love the videos!
