### ISSUE TITLE
Error: net_connect_unix(/var/run/dovecot/stats-writer) failed: Permission denied))

### ISSUE THREAD

**Issue by tzcrawford** [LukeSmithxyz/emailwiz#87]
I was having issues with my mailq and inbox population upon initial setup on my debian 10 system, and I came about the error `Error: net_connect_unix(/var/run/dovecot/stats-writer) failed: Permission denied))`. I think it has to do with an [upstream dovecot default permissions bug on debian systems](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=903161). I am using dovecot-imapd 1:2.3.4.1-5+deb10u4 amd64 when I experience the error. 

I managed to solve the issue by adding the following to dovecot.conf:
```
service stats {
    unix_listener stats-reader {
    user = vmail
    group = vmail
    mode = 0660
    }
    unix_listener stats-writer {
    user = vmail
    group = vmail
    mode = 0660
    }
}
```
For security reasons, I don't recommend setting mode 666.

With some further research, I think adding your user to the dovecot group may also help.

**Comment by swany7** [comment]
debian 11, dovecot 2.3.13 
stats-writer 
mode = 0666 
i cannot make start install of postfixadmin

adding dovecot and www-data to vmail gropup don't resolve(
