### ISSUE TITLE
How do setup multiple domains on the same server?

### ISSUE THREAD

**Issue by sarrost** [LukeSmithxyz/emailwiz#90]
I was originally going to email Luke directly but decided that such a question would be better asked here.

I currently have a single domain setup (say `example.com`) with `emailwiz`, and I want to also setup another mail domain (say `another.com`) on the same server. I was wondering if anyone has had any luck setting up multiple domains? It doesn't matter to me if there would be collisions for example `sarrost@example.com` and `sarrost@another.com` sending and receiving the same mail.

Kindly close this if such questions are not allowed here.

**Comment by et-8** [comment]
You could try the solution in this issue #38. I haven't tried it myself yet. If it works for you please let me know.
