### ISSUE TITLE
Cant log in to thunderbird 

### ISSUE THREAD

**Issue by BlutopiaHub** [LukeSmithxyz/emailwiz#94]
Im trying to log in to my email server with thunderbird
i put it all the information i need using the manual config

here are my settings

```
your name israel
email address israel@blutopia.ca

IMAP hostname mail.blutopia.ca port 993 SSL SSL/TLS Authentication Normal Password
SMTP mail.blutopia.ca port 587 SSL Auto Authentication  Normal Password

usernme incoming israel outgoing israel
```

when i test it just says "Thunderbird failed to find the settings for your email account"

**Comment by LukeSmithxyz** [comment]
If you only just ran the script, check the README: I made a change recently. Your login name should no longer just be your username, but your whole email address.

See if that's the problem.

**Comment by domdit** [comment]
Hey Luke,

Thanks for the script.

I am also unable to log in via Thunderbird. Getting the same error as the user above. I am using Ubuntu 20.10.
Thunderbird never gets past 'Probing Server' step.
I tried both whole email address and just the user.

At first I wondered if it was my ufw settings?

```
To                         Action      From
--                         ------      ----
22/tcp                     ALLOW       Anywhere
80/tcp                     ALLOW       Anywhere
443/tcp                    ALLOW       Anywhere
22/tcp (v6)                ALLOW       Anywhere (v6)
80/tcp (v6)                ALLOW       Anywhere (v6)
443/tcp (v6)               ALLOW       Anywhere (v6)
```

I am able to hit mail.domdit.com with proper 404 with ssl 

<img width="483" alt="Screen Shot 2020-11-18 at 9 59 22 PM" src="https://user-images.githubusercontent.com/13441577/99615414-5ed3f500-29e9-11eb-808b-3d149e7a29d3.png">

I reloaded nginx, I restarted the server.

**Comment by domdit** [comment]
It is a port issue...

**Comment by domdit** [comment]
Allowing ports 993 and 587 with ufw allowed me to log in. Please add to readme.
