### ISSUE TITLE
Can't receive or send mail

### ISSUE THREAD

**Issue by esobrev** [LukeSmithxyz/emailwiz#95]
I followed the installation instructions. When I added an account on neomutt using [mutt-wizard](https://github.com/LukeSmithxyz/mutt-wizard) of which no errors were received. I sent a test email and did not recieve it, and when checking my server there is no mail in the inbox there either. When I tried sending a test email I got the response from neomutt:
`msmtp: cannot connect to mail.<domain>, port 587: Connection refused
msmtp: could not send mail (account verbose@<domain> from /home/verb/.config/msmtp/config)`

I'm happy to provide any more evidence one may need to find the problem. Note that I censored my domain with `<domain>`. Thanks

**Comment by esobrev** [comment]
Here are the contents of `/home/verb/.config/msmtp/config`:

`tls     on
tls_trust_file  /etc/ssl/certs/ca-certificates.crt
logfile /home/verb/.config/msmtp/msmtp.log

account verbose@<domain>
host mail.<domain>
port 587
from verbose@<domain>
user verbose@<domain>
passwordeval "pass mw-verbose@<domain>"`

As before I have censored my domain name with `<domain>` and since my original opening of this issue have checked again that the TXT DNS records are copied over to my domain manager correctly.

**Comment by LukeSmithxyz** [comment]
This is your own mail server then? Have you opened up all mail submission ports (which might include asking your VPS provider to open them)?

**Comment by esobrev** [comment]
I have solved my issue by changing the certpath for dovecot from `mail.<domain>` to `<domain>` in `/etc/dovecot/dovecot.conf` as well as editing my hostname to be my domain name instead of localhost in `/etc/postfix/main.cf`. I'm unsure whether these errors in configuration were at the fault of your script or if they were do to my server configuration.
