### ISSUE TITLE
No DKIM signature on emails

### ISSUE THREAD

**Issue by esobrev** [LukeSmithxyz/emailwiz#96]
I apologize for making a second issue so soon after the last one. 

When I do a [DKIM test](https://www.appmaildev.com/en/dkim) I get the return `DKIM-Result: none (no signature)`. 

`journalctl -xe | grep "DKIM"` does not show any problems with OpenDKIM starting. `systemctl status opendkim.service` shows it running with an error which says `opendkim.service: Can't open PID file /run/opendkim/opendkim.pid (yet?) after` but this is just a warning so I don't think this is it. [#28 ](https://github.com/LukeSmithxyz/emailwiz/issues/28) said to add the -h option to the registrar, I did that and that did not work either.

**Comment by LukeSmithxyz** [comment]
Did you double check the DKIM entry you put into your DNS settings?

**Comment by portalreaper** [comment]
For myself, I get DKIM-Result: permerror (no key).

For the host, I've tried mail._domainkey and mail._domainkey.domain.xyz and no dice.

`journalctl -xe | grep DKIM
systemd[1]: Starting OpenDKIM DomainKeys Identified Mail (DKIM) Milter...
systemd[1]: Started OpenDKIM DomainKeys Identified Mail (DKIM) Milter.
opendkim[487]: OpenDKIM Filter v2.11.0 starting (args: -x /etc/opendkim.conf)`

Nothing suspicious here? Should I edit/uncomment something on `opendkim.conf`? All files within check out and it looks proper.

**Comment by esobrev** [comment]
LukeSmithxyz: yes I'm sure that the DKIM entry in my DNS records is correct.

**Comment by kp9001** [comment]
Have you tried replacing the DKIM entry produced by the script with the one located in `/etc/postfix/dkim/mail.txt`? I had the same issue and tried this. I had to edit the output by removing all parentheses, but then it worked.

**Comment by esobrev** [comment]
Yes, when I said that I added the -h option to the registrar, that was the only thing that was different between the one in `.dns_emailwizard` and in `/etc/postfix/dkim/mail.txt`. Was there any other differences in yours? The quotes?

**Comment by kp9001** [comment]
First of all, I had a typo in my previous message, when I wrote "parentheses" I meant "quotations". Sorry!

Anyway, in my case they were the same in content but quite different in formatting. Let me replace the two long strings in the DKIM tx with `abc` and `123`. Then `dns_emailwizard` had the dkim tx listed as

```
v=DKIM1; k=rsa; p=abc123
```

whereas `/etc/postfix/dkim/mail.txt` had the dkim tx listed as 

```
"v=DKIM1; h=sha256; k=rsa; "
        "p=abc"
        "123"
```

I removed all quotations from the second one but left in all the spaces, including the tabbed spaces, and suddenly it worked.

**Comment by portalreaper** [comment]
Yeah, see #18.

**Comment by esobrev** [comment]
Issue has been fixed by doing what kp9001 suggested. I'm now wondering what caused this issue to occur in the first place, if a contibuter has any questions as to my specific setup parameters please let me know. Thank you for all who helped.
