### ISSUE TITLE
Invalid $certdir for wildcard TLS certificate

### ISSUE THREAD

**Issue by JoshuaS3** [LukeSmithxyz/emailwiz#98]
emailwiz.sh looks for `mail.[domain]` after `Domains: ` in the output of `certbot certificates`.

This fails when the certificate uses a (valid) wildcard:
```
    Domains: [domain] *.[domain]
```

The certificate is valid but the certificate directory (`$certdir`) can't be parsed from the output of `certbot certificates`. This leads to incorrect postfix and dovecot configuration.

**Comment by ItsSynergi** [comment]
Ran into this issue as well and had to work around it.

**Comment by LukeSmithxyz** [comment]
Should be fixed in b50fb342f12ad6a0bc296bc9f80afa82a859868f
