### ISSUE TITLE
nginx server necessary?

### ISSUE THREAD

**Issue by toluschr** [LukeSmithxyz/emailwiz#99]
In [Line 52](https://github.com/LukeSmithxyz/emailwiz/blob/master/emailwiz.sh#L51) of the script and at [4:50](https://youtu.be/9zP7qooM4pY?t=291) of your video, you say that one needs to setup an nginx server to have certbot deploy the certificates.
However, I found a guide [How to secure Postfix using Let's Encrypt - Tutorial - UpCloud](https://upcloud.com/community/tutorials/secure-postfix-using-lets-encrypt#point-3) that doesn't use nginx to get the certificates.
Instead, they use the following command: `certbot certonly --standalone -d mail.example.com`.

My question is, whether it's necessary / recommended to have an additional nginx server running.

**Comment by LukeSmithxyz** [comment]
It probably is fine, but I only say that because I haven't experimented with it without nginx. I mean there's no actual command in the script that really requires it, so I might change the README to that effect.
